### ISSUE TITLE
Errors on full editor area.

### ISSUE THREAD

**Issue by pyvim** [atom-community/linter#931] opened 2015-10-06 05:42 UTC
![Screenshot](http://oi61.tinypic.com/2ikorm.jpg)

**Comment by blakeembrey** [comment] 2015-10-06 06:09
@pyvim Do you have more information? I don't know what the issue is here? Did you drag it up there? Did you ever drag it? What's the maximum height you have set? You can find it in your config (if you dragged it up before it'll expand to fill it once there's enough errors). Is this only in full screen like the title says?

**Comment by pyvim** [comment] 2015-10-06 06:19
@blakeembrey, hello. It happened after update to 1.8.1. I don't drag it, don't change maximum height. It happened when have unclosed {"[' in code. On screenshot only Atom window. Errors occupy the entire area of the editor.

**Comment by blakeembrey** [comment] 2015-10-06 06:21
@pyvim Ok, thanks - can you tell me what the number in your config is (under `linter` package)? It's possible that it's not currently a number and perhaps that's causing the maximum to fail (might be my fault for assuming Atom would validate this properly). You can always drag it down to take up less space too.

**Comment by blakeembrey** [comment] 2015-10-06 06:31
![image](https://cloud.githubusercontent.com/assets/1088987/10301581/aa93df22-6bb8-11e5-80e0-f7f2a9c22339.png)

^ That one. I'll keep this open to make sure a better maximum bound check is implemented in the future. We should really make sure that we don't fill the entire window in any case. The algorithm needs to look something like `min(total of visible pane heights - 100, 100)` to handle cases on each end of the spectrum.

**Comment by pyvim** [comment] 2015-10-06 06:35
@blakeembrey, where I can find field "Error Panel Height"?

**Comment by blakeembrey** [comment] 2015-10-06 06:39
In the package settings of `linter`, under preferences (`cmd + ,` on Mac).

**Comment by pyvim** [comment] 2015-10-06 06:43
All settings (bellow Keybindings).
![Settings](http://oi59.tinypic.com/2e65t3l.jpg)

**Comment by blakeembrey** [comment] 2015-10-06 06:51
That's weird, it's not even there. It should be between two of those options, I wonder if this is an Atom issue?

![image](https://cloud.githubusercontent.com/assets/1088987/10301880/d2e536ee-6bbb-11e5-8936-5117c556ba71.png)

What if you set `linter.errorPanelHeight` and `linter.alwaysTakeMinimumSpace` yourself manually? Anyone else run into this issue?

**Comment by pyvim** [comment] 2015-10-06 06:59
@blakeembrey, thaks, it's worked.
In `config.cson` was: `linter: {}`.
I set
`linter: {
errorPanelHeight: 150
alwaysTakeMinimumSpace: true
}` and fields appeared in Linter settings.

**Comment by ismay** [comment] 2015-10-06 09:28
I'm having the same issue. Errors filling entire screen, and no available settings in `packages/linter` (it just shows the readme).

**Comment by steelbrain** [comment] 2015-10-06 09:45
Did you try changing your theme? We've had reports like this with people using buggy themes.

**Comment by pyvim** [comment] 2015-10-06 09:51
@steelbrain, after [my changes](https://github.com/atom-community/linter/issues/931#issuecomment-145762834) fields appeared, but theme not changed (I using [atom-material-ui](https://github.com/silvestreh/atom-material-ui)).

**Comment by Xety** [comment] 2015-10-06 11:38
You need to restart Atom after the last update. I had the same error and i restarted Atom, now it work like before. (Theme : atom-material-ui)

**Comment by steelbrain** [comment] 2015-10-06 13:13
Closing based on comment above. Let us know if it doesn't solve your problem however.

**Closed by steelbrain** 2015-10-06 13:13 UTC
