### ISSUE TITLE
Separate Errors and Warnings

### ISSUE THREAD

**Issue by JamesCoyle** [atom-community/linter#907] opened 2015-09-28 14:58 UTC
Currently there is an indicator for the total number of issues in the project.
![image](https://cloud.githubusercontent.com/assets/10384436/10138949/9e356f9a-65f8-11e5-9347-69263e6c1487.png)

It would be useful if it showed the number of errors and warnings separately as togglable buttons. Most of the time I want the errors displayed in the log but can ignore a lot of the warnings so don't want them visible all the time. It would also be nice if it adjusted the number based on whether file or project was selected to the left of it.

**Comment by steelbrain** [comment] 2015-09-28 15:05
We have considered it in the past but it comes with a lot of complexity and even some performance penalty. We have not been able to put together enough time for this, besides, once we consider it, other questions start to arise like will it only contain warnings and errors or all the types if it will contain all the types, how will the toggle be persistent? how will we have dynamic configs? Will they be persistent per project or globally?
I would love to have them answered and eventually accept a PR :)

**Comment by steelbrain** [comment] 2015-10-09 07:25
Dupe of #878

**Closed by steelbrain** 2015-10-09 07:25 UTC
Labels: feature request, priority-low
