### ISSUE TITLE
Uncaught TypeError: Invalid Point: (27, NaN)

### ISSUE THREAD

**Issue by aubrian-halili-ags** [atom-community/linter#1048] opened 2016-01-19 08:21 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.3

### Stack Trace

Uncaught TypeError: Invalid Point: (27, NaN)

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63

TypeError: Invalid Point: (27, NaN)
    at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1015:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1003:20)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:204:46)
    at TextEditorMarkerLayer.module.exports.TextEditorMarkerLayer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker-layer.js:78:52)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1100:38)
    at TextEditor.module.exports.TextEditor.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1339:59)
    at /Users/aubrianhalili/.atom/packages/linter/lib/editor-linter.js:50:34
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at EditorLinter.addMessage (/Users/aubrianhalili/.atom/packages/linter/lib/editor-linter.js:137:20)
    at /Users/aubrianhalili/.atom/packages/linter/lib/linter-views.js:104:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (/Users/aubrianhalili/.atom/packages/linter/lib/linter-views.js:102:11)
    at LinterViews.render (/Users/aubrianhalili/.atom/packages/linter/lib/linter-views.js:59:10)
    at /Users/aubrianhalili/.atom/packages/linter/lib/linter.coffee:39:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at MessageRegistry.updatePublic (/Users/aubrianhalili/.atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (/Users/aubrianhalili/.atom/packages/linter/lib/message-registry.js:24:16)
```

### Commands

```
     -0:13.4.0 project-manager:list-projects (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "linter": {
    "errorPanelHeight": 171
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
color-picker, v2.0.14
docblockr, v0.7.3
emmet, v2.3.18
file-icons, v1.6.14
highlight-line, v0.11.0
highlight-selected, v0.11.1
linter, v1.11.3
linter-jshint, v1.2.2
minimap, v4.19.0
pigments, v0.19.7
project-manager, v2.7.3

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2016-01-19 09:04
That is a very interesting error you hit there, can you please provide a repro for this?

**Comment by rshackleton-netc** [comment] 2016-01-20 11:58
Had the same issue, have not been able to reproduce it reliably.

**Atom Version**: 1.4.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.3


### Stack Trace

Uncaught TypeError: Invalid Point: (17, NaN)

```
At C:\Users\RShackleton\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\text-buffer\lib\point.js:63

TypeError: Invalid Point: (17, NaN)
    at Function.module.exports.Point.assertValid (C:\Users\RShackleton\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\text-buffer\lib\point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (C:\Users\RShackleton\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1015:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (C:\Users\RShackleton\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1003:20)
    at MarkerLayer.module.exports.MarkerLayer.markRange (C:\Users\RShackleton\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\text-buffer\lib\marker-layer.js:204:46)
    at TextEditorMarkerLayer.module.exports.TextEditorMarkerLayer.markBufferRange (C:\Users\RShackleton\AppData\Local\atom\app-1.4.0\resources\app.asar\src\text-editor-marker-layer.js:78:52)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (C:\Users\RShackleton\AppData\Local\atom\app-1.4.0\resources\app.asar\src\display-buffer.js:1100:38)
    at TextEditor.module.exports.TextEditor.markBufferRange (C:\Users\RShackleton\AppData\Local\atom\app-1.4.0\resources\app.asar\src\text-editor.js:1339:59)
    at C:/Users/RShackleton/.atom/packages/linter/lib/editor-linter.js:50:34
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\RShackleton\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\RShackleton\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at EditorLinter.addMessage (C:/Users/RShackleton/.atom/packages/linter/lib/editor-linter.js:137:20)
    at C:/Users/RShackleton/.atom/packages/linter/lib/linter-views.js:104:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (C:/Users/RShackleton/.atom/packages/linter/lib/linter-views.js:102:11)
    at LinterViews.render (C:/Users/RShackleton/.atom/packages/linter/lib/linter-views.js:59:10)
    at file:///C:/Users/RShackleton/.atom/packages/linter/lib/linter.coffee:39:14
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\RShackleton\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\RShackleton\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at MessageRegistry.updatePublic (C:/Users/RShackleton/.atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (C:/Users/RShackleton/.atom/packages/linter/lib/message-registry.js:24:16)
```

### Commands

```
     -0:17.4.0 core:select-up (atom-text-editor.editor.is-focused)
     -0:17.1.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:16.4.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:16.1.0 core:select-up (atom-text-editor.editor.is-focused)
     -0:15.7.0 core:cut (atom-text-editor.editor.is-focused)
  3x -0:15.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:14.7.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:14.4.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:14.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:12.8.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
 15x -0:12 core:move-up (atom-text-editor.editor.is-focused)
     -0:10.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:10.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:10 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:10 snippets:expand (atom-text-editor.editor.is-focused)
     -0:10 editor:indent (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "emmet"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.21
atom-tfs-auto, v0.2.0
color-picker, v2.0.14
language-aspx, v0.4.0
linter, v1.11.3
linter-jshint, v1.2.2
minimap, v4.19.0
minimap-linter, v1.1.1
minimap-pigments, v0.1.7
pigments, v0.19.7
project-manager, v2.7.3

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment] 2016-01-20 23:18
Looks like both of you only have `linter-jshint` installed as a linter provider, so I'm assuming it's passing in an invalid range, but we should be validating it here before attempting to send it off to Atom for markup in any case.

If you could find a file that reproduces this that would be most helpful!

**Comment by dimonnwc3** [comment] 2016-01-21 11:21
[Enter steps to reproduce below:]

1.Open JS File

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.3
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.3


### Stack Trace

Uncaught TypeError: Invalid Point: (123, NaN)

```
At /opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63

TypeError: Invalid Point: (123, NaN)
    at Function.module.exports.Point.assertValid (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1015:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1003:20)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:204:46)
    at TextEditorMarkerLayer.module.exports.TextEditorMarkerLayer.markBufferRange (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/src/text-editor-marker-layer.js:78:52)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1100:38)
    at TextEditor.module.exports.TextEditor.markBufferRange (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1339:59)
    at /Users/dimonn/.atom/packages/linter/lib/editor-linter.js:50:34
    at Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at EditorLinter.addMessage (/Users/dimonn/.atom/packages/linter/lib/editor-linter.js:137:20)
    at /Users/dimonn/.atom/packages/linter/lib/linter-views.js:104:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (/Users/dimonn/.atom/packages/linter/lib/linter-views.js:102:11)
    at LinterViews.render (/Users/dimonn/.atom/packages/linter/lib/linter-views.js:59:10)
    at /Users/dimonn/.atom/packages/linter/lib/linter.coffee:39:14
    at Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.2.4/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at MessageRegistry.updatePublic (/Users/dimonn/.atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (/Users/dimonn/.atom/packages/linter/lib/message-registry.js:24:16)
```

### Commands

```
     -0:07.2.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:07.1.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "about",
      "archive-view",
      "autoflow",
      "background-tips",
      "bookmarks",
      "deprecation-cop",
      "dev-live-reload",
      "go-to-line",
      "metrics",
      "styleguide",
      "welcome",
      "package-generator",
      "symbols-view"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "linter": {
    "gutterPosition": "Left"
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-material-syntax, v0.2.10
atom-material-ui, v0.8.0
autocomplete-paths, v1.0.2
color-picker, v2.0.14
emmet, v2.3.18
file-icons, v1.6.14
highlight-selected, v0.11.1
language-ejs, v0.2.0
language-jade, v0.6.2
linter, v1.11.3
linter-jshint, v1.2.2
pigments, v0.20.0
symbols-tree-view, v0.11.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment] 2016-01-21 17:58
@aubrian-halili-ags @rshackleton-netc @dimonnwc3 

Without a file that triggers this we can't debug what is going on, do any of you have some code that triggers this that you can share? Or steps to reproduce this?

**Comment by RShackleton** [comment] 2016-01-21 18:34
Unfortunately it happened for me when I opened a comment (/*) and a function was commented out before I closed it. I tried following the same steps but the error didn't appear again.

**Comment by mmoulton** [comment] 2016-01-25 23:18
I ran into this today. Here is an example that makes it happen for my setup.

Given this file:
```js
var item = { item1: 'item1', _item2: 'item2' },
    value = item['_item2'];
```

Edit it so that you remove the `['` to get `item_item2`. This causes the Invalid Point issue every time for me.

**Comment by Arcanemagus** [comment] 2016-01-26 17:07
@mmoulton, @aubrian-halili-ags, @rshackleton-netc, @dimonnwc3: I'm pretty sure this is due to the [`esprima` bug](https://github.com/jquery/esprima/issues/1457) that has been cropping up all over the place lately, probably due to us actually warning about it instead of silently ignoring the invalid input.

I would recommend using a JS linter that allows specifying an alternative parser such as [linter-eslint](https://github.com/AtomLinter/linter-eslint) or [linter-jscs](https://github.com/AtomLinter/linter-jscs).

`jshint` in particular seems to blow up rather badly on this bug, exploding the single issue into 3 different ones (one of which triggers this bug), while the other linters (when using `esprima`) simply have a single bug with an incorrect column. You can verify that this is an issue with the linter itself by running it from a terminal and checking the output for column's past the end of the line.

I'm marking this as closed since this is almost certainly an issue with the linter program itself. Feel free to keep posting here though if you have further questions.

**Closed** 2016-01-26 17:08 UTC

**Comment by steelbrain** [comment] 2016-01-26 17:09
Another bug that is triggered on `this_kinda_case` in jshint https://github.com/jshint/jshint/pull/2846
