### ISSUE TITLE
Toggle different linter enabled/disabled per atom instance

### ISSUE THREAD

**Issue by blakeembrey** [atom-community/linter#999] opened 2015-11-12 23:15 UTC
Sometimes I'm working on a project that doesn't follow Standard JS or TSLint default, and for those I don't want the linter running the linters that I don't use. Is it possible to show a way to enable/disable linters per-project have this cached (maybe using the root project open as the key?)

**Comment by steelbrain** [comment] 2015-11-13 05:45
Dupe of #744?

**Comment by blakeembrey** [comment] 2015-11-13 06:15
Yes, looks like it is. It's a different implementation though. I would be against the editor specific files in my project, that absolutely doesn't make sense. Feel free to close this, but please copy my thoughts across. 

As for the UI, it should be minimal and integrated into the bottom panel. I would have an initial line or something that says the sources currently in the bottom panel and allow them to be checked on and off via a select box.

**Comment by steelbrain** [comment] 2015-11-13 06:16
@blakeembrey The title of the issue could be misleading, but the purpose of it is to come up with a good solution of enabling/disabling linters per project

**Comment by kepler0** [comment] 2015-11-13 06:49
*cough* Amazing Issue Number *cough*

**Comment by steelbrain** [comment] 2015-11-13 16:36
Closing in favor of issue mentioned above

**Closed by steelbrain** 2015-11-13 16:36 UTC
