### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTokenIterator' of undefined

### ISSUE THREAD

**Issue by minicast** [atom-community/linter#650] opened 2015-06-27 20:31 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0-3874576
**System**: Ubuntu 15.04
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v1.0.9

### Stack Trace

Uncaught TypeError: Cannot read property 'getTokenIterator' of undefined

```
At /usr/local/share/atom/resources/app.asar/src/tokenized-buffer.js:660

TypeError: Cannot read property 'getTokenIterator' of undefined
    at TokenizedBuffer.module.exports.TokenizedBuffer.scopeDescriptorForPosition (/usr/local/share/atom/resources/app.asar/src/tokenized-buffer.js:660:42)
    at DisplayBuffer.module.exports.DisplayBuffer.scopeDescriptorForBufferPosition (/usr/local/share/atom/resources/app.asar/src/display-buffer.js:1135:35)
    at TextEditor.module.exports.TextEditor.scopeDescriptorForBufferPosition (/usr/local/share/atom/resources/app.asar/src/text-editor.js:2281:33)
    at EditorLinter.lint (/home/minicast/.atom/packages/linter/lib/editor-linter.coffee:101:28)
    at /home/minicast/.atom/packages/linter/lib/editor-linter.coffee:34:26
    at Emitter.module.exports.Emitter.emit (/usr/local/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at /usr/local/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1183:25
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "solarized-light-syntax"
    ],
    "disabledPackages": [
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-java",
      "language-objective-c",
      "language-yaml",
      "language-toml",
      "linter-jscs",
      "linter-jshint",
      "tree-view"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
atom-zeal, v0.1.3
linter, v1.0.9
linter-coffeelint, v0.3.2
linter-eslint, v1.0.8
make-coffee, v0.1.1
meteor-api, v2.19.0
minimap, v4.10.0
nuclide-code-format, v0.0.22
nuclide-diff-view, v0.0.22
nuclide-file-tree, v0.0.22
nuclide-file-watcher, v0.0.22
nuclide-flow, v0.0.22
nuclide-hack, v0.0.22
nuclide-hg-repository, v0.0.22
nuclide-installer, v0.0.22
nuclide-language-hack, v0.0.22
nuclide-remote-projects, v0.0.22
nuclide-type-hint, v0.0.22

# Dev
No dev packages
```

**Comment by k2b6s9j** [comment] 2015-06-27 20:32
What were you attempting to do when this error occurred?

**Comment by steelbrain** [comment] 2015-06-27 20:32
Can you please provide a minimal repro case?

**Comment by minicast** [comment] 2015-06-28 13:44
The error appeared just after starting up the program (i did not have 
time to do anything specific).

**Comment by karabuta** [comment] 2015-06-29 15:32
Yes same here. The error just pops up right after startup in the notification dialog.

**Comment by iam4x** [comment] 2015-06-29 15:35
@minicast @karabuta Are you using Nuclide?

(@steelbrain you are using nuclide too right?)

**Comment by steelbrain** [comment] 2015-06-29 20:47
@iam4x I have friends that have tested it without encountering this bug. I tried like a week ago and this bug wasn't there.
Not sure what the 'cause is.

**Comment by iam4x** [comment] 2015-06-29 20:58
@steelbrain Going to try nuclide with the same packages.

**Comment by steelbrain** [comment] 2015-06-29 20:59
:+1:

**Comment by iam4x** [comment] 2015-06-29 21:45
Are you using Ubuntu @karabuta ?

**Comment by minicast** [comment] 2015-06-29 21:48
yes, i had nuclide when the error occurred (full packages-list included 
in report)

**Comment by Eschon** [comment] 2015-06-30 06:42
I started up Atom in with `atom .` in my project folder and when the window opened I got this error. It startet on a `.js` file if maybe that has to do with it and I don't use nuclide.

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v1.1.0


### Stack Trace

Uncaught TypeError: Cannot read property 'getTokenIterator' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:660

TypeError: Cannot read property 'getTokenIterator' of undefined
    at TokenizedBuffer.module.exports.TokenizedBuffer.scopeDescriptorForPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:660:42)
    at DisplayBuffer.module.exports.DisplayBuffer.scopeDescriptorForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1135:35)
    at TextEditor.module.exports.TextEditor.scopeDescriptorForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2281:33)
    at EditorLinter.lint (/Users/egon/.atom/packages/linter/lib/editor-linter.coffee:106:28)
    at /Users/egon/.atom/packages/linter/lib/editor-linter.coffee:39:26
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1183:25
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "disabledPackages": [
      "image-view",
      "background-tips",
      "language-go",
      "language-less",
      "language-property-list",
      "language-todo",
      "language-toml",
      "spell-check",
      "bookmarks",
      "welcome",
      "autoflow",
      "markdown-preview",
      "go-to-line",
      "language-c",
      "language-csharp",
      "language-java",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "package-generator",
      "linter-tidy"
    ]
  },
  "linter": {
    "showInfoMessages": true,
    "subtleLinterErrors": [
      "jscs",
      "jshint"
    ],
    "clearOnChange": true,
    "showHighlighting": false,
    "defaultErrorTab": "Line",
    "showErrorTabLine": true,
    "showErrorTabProject": false,
    "showErrorInline": false
  }
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v0.5.0
atom-ternjs, v0.6.7
color-picker, v2.0.7
linter, v1.1.0
linter-csslint, v0.0.14
linter-jscs, v1.12.0
linter-jshint, v0.1.7
linter-rubocop, v0.2.7
linter-xmllint, v0.0.7
pretty-json, v0.4.1
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2015-06-30 06:44
I know what the problem is, and I have a fix planned.

**Comment by lazutkin** [comment] 2015-06-30 19:12
:+1:

**Comment by steelbrain** [comment] 2015-07-05 17:35
I think this is fixed by https://github.com/AtomLinter/Linter/pull/664
can someone confirm?

**Comment by Eschon** [comment] 2015-07-10 06:39
Is this fix released? Just got the error again.

**Comment by steelbrain** [comment] 2015-07-10 06:40
@Eschon could you please provide us a minimal repro case?

**Comment by Eschon** [comment] 2015-07-10 06:47
@steelbrain I just started Atom from the command line in my project. It started on a `.js` file and the error appeared. There is also a second error which points to #510 but with a different stack trace.

**Comment by steelbrain** [comment] 2015-07-10 06:48
Sounds like an upgrade issue. Can you flush your caches and retry?

**Comment by Eschon** [comment] 2015-07-10 06:54
How do I flush my chaches in Atom?

**Comment by steelbrain** [comment] 2015-07-10 06:55
```
mv ~/.atom ~/.atom-bkp
apm install linter
```

**Comment by Eschon** [comment] 2015-07-10 07:05
Ok thanks, seems to work now.

**Comment by Eschon** [comment] 2015-07-14 07:00
Suddenly the error is back now it happens on an `.edn` file that isn't even checked by any `linter-` package that I have installed as far as I know.

**Comment by steelbrain** [comment] 2015-07-25 12:32
Does this still happen with the master branch? We've split out a lot of stuff and have super-simplified it, and I believe fixed this one along the way.

**Comment by minicast** [comment] 2015-07-26 15:02
It didn't happen to me lately

**Comment by steelbrain** [comment] 2015-07-26 15:03
I am glad it didn't

**Closed by steelbrain** 2015-07-26 15:03 UTC
Labels: unconfirmed bug
