### ISSUE TITLE
Uncaught TypeError: Invalid Point: (53, NaN)

### ISSUE THREAD

**Issue by balmasich** [atom-community/linter#1078] opened 2016-02-11 07:14 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.1
**System**: Mac OS X 10.11.4
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.3

### Stack Trace

Uncaught TypeError: Invalid Point: (53, NaN)

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63

TypeError: Invalid Point: (53, NaN)
    at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1015:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1003:20)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:204:46)
    at TextEditorMarkerLayer.module.exports.TextEditorMarkerLayer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker-layer.js:78:52)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1103:38)
    at TextEditor.module.exports.TextEditor.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1367:59)
    at /Users/b/.atom/packages/linter/lib/editor-linter.js:50:34
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at EditorLinter.addMessage (/Users/b/.atom/packages/linter/lib/editor-linter.js:137:20)
    at /Users/b/.atom/packages/linter/lib/linter-views.js:104:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (/Users/b/.atom/packages/linter/lib/linter-views.js:102:11)
    at LinterViews.render (/Users//.atom/packages/linter/lib/linter-views.js:59:10)
    at /Users/b/.atom/packages/linter/lib/linter.coffee:39:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at MessageRegistry.updatePublic (/Users/b/.atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (/Users/b/.atom/packages/linter/lib/message-registry.js:24:16)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "emmet",
      "tidy-markdown",
      "bookmarks",
      "jshint",
      "linter-eslint"
    ]
  },
  "linter": {
    "showErrorTabLine": true
  }
}
```

### Installed Packages

```coffee
# User
atom-sync, v0.6.0
docblockr, v0.7.3
editorconfig, v1.2.4
gtk-dark-theme, v0.1.4
highlight-line, v0.11.1
highlight-selected, v0.11.2
javascript-snippets, v1.2.1
language-babel, v2.15.3
language-docker, v1.1.6
language-javascript-jsx, v0.3.7
linter, v1.11.3
linter-jshint, v1.3.1
linter-jsonlint, v1.1.5
linter-sass-lint, v1.0.5
markdown-preview-plus, v2.2.2
markdown-preview-plus-opener, v0.2.0
minimap, v4.19.0
minimap-autohide, v0.10.1
project-manager, v2.7.6

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2016-02-11 07:38
Dupe of #1048 #1053 #1058 #1059 #1061 #1062 #1065 #1068 #1060 #1063 #1064 #1066  #1069 #1070 #1071 #1072 #1074 #1076

**Closed by steelbrain** 2016-02-11 07:38 UTC
