### ISSUE TITLE
Clicking issues in the status bar searches throughout the project even if scope is set to "File"

### ISSUE THREAD

**Issue by josh18** [atom-community/linter#1080] opened 2016-02-11 20:17 UTC
Expected: When the file is set to scope I expected clicking on the issues in the status bar to scroll through the issues in that file.

Observed: Clicking on the issues scrolls to all issues in the project.

Not sure if this is intended or not but it was a little confusing for me.

**Comment by steelbrain** [comment] 2016-02-11 23:37
Not sure what you mean by `Clicking on the issues scrolls to all issues in the project`, but when you switch to the file tab, only the messages matching the current file path will be shown and everything else will be hidden. But if you have a trace in those errors that points to other files, clicking that trace will take you there and it should

**Comment by josh18** [comment] 2016-02-12 00:20
![image](https://cloud.githubusercontent.com/assets/5900962/12995249/fb46aa02-d18a-11e5-960b-4ecbec65102a.png)
For example the above image correctly states that I have two issues in my current file. However if I click on it scrolls me through all the issues in my current project (changes the active tab) rather than just scrolling to the two issues in my current file. Does that make sense?

**Comment by steelbrain** [comment] 2016-02-12 01:04
Please note that the use of that button is highly discouraged and it'll be removed in the near future, we will however keep the command that takes user to the next error

Also this is a dupe of https://github.com/atom-community/linter/issues/833

**Closed by steelbrain** 2016-02-12 01:04 UTC
Labels: question
