### ISSUE TITLE
linter makes window jump up and down very quickly

### ISSUE THREAD

**Issue by gkrawiec** [atom-community/linter#779] opened 2015-07-30 23:49 UTC
If there is a line linter has detected has an issue and you select that line and start dragging to a line without issues, there is a zone where the screen starts jumping up and down. Here is a screencast of it happening.
[linter is jumpy.mp4 | uploaded via ZenHub](https://files.zenhub.io/55bab7ab9c00db7373528833)

**Comment by steelbrain** [comment] 2015-07-31 02:46
That is weird, anyways, can you repro that with the master branch?

**Comment by gkrawiec** [comment] 2015-07-31 02:57
Sorry, I dont know what this means "repro that with the master branch". (just started to learn programming).
The problem seems to be that when the linter error shows up on the bottom, it pushes the problem line up, so the error line on the bottom disappears, so it jumps back down. This starts the cycle. It makes using the mouse to select some specific lines impossible (with keyboard it doest make a difference since the cursor moves with the screen as it goes up when the error is displayed)
It would be nice if the display of errors on the bottom doesnt move the whole pane upwards.
By the way, this problem only started showing up after you redesigned everything on v1. It wasnt there at all before.

**Comment by steelbrain** [comment] 2015-07-31 03:02
Can you please confirm that you are not on a virtual machine?

**Comment by gkrawiec** [comment] 2015-07-31 03:04
I am NOT on a virtual machine.

**Comment by steelbrain** [comment] 2015-07-31 03:05
Okay, so do you have `git` installed? Can you confirm that this fixes your problem?
```
cd ~/.atom/packages
rm -rf linter
git clone https://github.com/atom-community/linter
cd linter
apm install
```

**Comment by gkrawiec** [comment] 2015-07-31 03:11
I closed atom
ran the commands
```
Last login: Mon Jul 27 10:45:25 on ttys002

me@mymachine at $ cd ~/.atom/packages

me@mymachine packages $ rm -rf linter

me@mymachine packages $ git clone https://github.com/atom-community/linter
Cloning into 'linter'...

remote: Counting objects: 6861, done.

remote: Compressing objects: 100% (22/22), done.

remote: Total 6861 (delta 9), reused 0 (delta 0), pack-reused 6839

Receiving objects: 100% (6861/6861), 1.03 MiB | 1.45 MiB/s, done.

Resolving deltas: 100% (4543/4543), done.

Checking connectivity... done.

me@mymachine packages $ cd linter

me@mymachine linter $ apm install

Installing modules ✓

me@mymachine linter $
```
opened atom from command line.....but the problem persists.

Would you like me to test something else?

**Comment by steelbrain** [comment] 2015-07-31 03:12
Can you please provide us a minimal repro case? I (or anyone from the team) haven't actually encountered it yet.

**Comment by gkrawiec** [comment] 2015-07-31 03:19
If you explain to me what you mean by "minimal repro case" I can provide it :)
not sure if it makes a difference, here is a list of my current packages...maybe something not getting along with something else?

```
README.md
Sublime-Style-Column-Selec
atom-beautify/
atomatigit/
git-history/
git-log/
hashrocket/
language-haml/
linter/
linter-erb/
linter-rubocop/
regex-railroad-diagram/
````

**Comment by steelbrain** [comment] 2015-07-31 03:20
repro = reproduction
Minimal repro case would mean a minimal way to reproduce the same linter behavior.

**Comment by gkrawiec** [comment] 2015-07-31 03:36
sure, this is the minimum required to see this in my setup
1) install linter + rubocop
2)open atom from command line 
3) split pane down
4) select "Show error of the selected line" by pressing "Line 1" on the bottom status bar
5) on bottom pane type
```
def test {}
end
```
6) linter will put a squiggly line under the the braces (Error: unexpected token tLCURLY at line 1 col 10)
7) put mouse cursor on line 1and then drag down slowly to the second line
8) you can also just click on the second line and drag upwards to the line with error

9)the problem starts when the cursor is about halfway up(or down) from the line with error into a line without error.

10)here are my linter settings if you need them. 
https://www.dropbox.com/s/x8kncopufil64yn/Screenshot%202015-07-30%2020.27.37.png?dl=0


hopefully this is enough to reproduce it on your side.

it seems to be the bottom pane that causes the jumps up and down

let me know if you need anything else.
thanks.

**Comment by steelbrain** [comment] 2015-07-31 03:38
Thanks for the repro case, now all we need is a person reproing it.

**Comment by gkrawiec** [comment] 2015-07-31 03:39
np. let me know if you need any other info or test.
thanks.

**Comment by steelbrain** [comment] 2015-08-12 07:05
Sorry man, no repro case for 12 days, gonna have to close this one.

**Comment by gkrawiec** [comment] 2015-08-12 17:29
the bug is still there. Even tried it on a fresh install on virtualbox windows guest. Feel free to close it, but the bug is still there.

**Comment by steelbrain** [comment] 2015-08-12 17:30
VirtualBox isn't supported by us, try searching for a `Gaming Mouse Integration`, or try vmware.

**Comment by gkrawiec** [comment] 2015-08-12 17:32
yes, but the initial report is on native osx (my daily machine)

**Comment by steelbrain** [comment] 2015-08-12 17:32
@atom-community/linter-contributors are you guys able to repro this?

**Comment by gkrawiec** [comment] 2015-08-12 17:33
maybe the bug is on the way panels work and not linter. I dont know enough
to know this....but it is definitely a problem.

**Comment by Arcanemagus** [comment] 2015-08-12 18:43
It looks like I can reproduce this, I'm assuming it's due to the fact that the bottom panel appearing (or disappearing) causes the cursor's selection to change, causing the "per line" message box to appear/disappear... causing the selection to change. Repeat until the cursor is moved by the user.

I'm not sure how you would fix this though, even putting a delay in there before closing the panel wouldn't fix this, just make it glitch slower.

**Comment by steelbrain** [comment] 2015-08-12 18:44
@Arcanemagus mind explaining it a bit more, I still don't know why is the panel closing/re-enabling so quickly

**Comment by Arcanemagus** [comment] 2015-08-12 18:48
When the cursor is on the `end` line the panel closes completely since there are no errors on that line. If the cursor is on the first line it pops up the error panel. Since the window is split down this causes the _screen position_ of the lines to change, by about half of a line of distance. Since you are doing a drag selection when this happens, and the cursor moves with the mouse during that, the current line the linter is using changes when the window moves. Since the line has changed the panel then updates to the status of the new line, causing another shift in the screen position of the lines.

**Comment by Arcanemagus** [comment] 2015-08-12 18:52
To put it another way:

1. Cursor on line 1, panel showing
1. Selection starts dragging from line 1 to line 2
1. Editor cursor moves to line 2
1. Panel disappears since there are no errors on line 2
1. Editor content gets shifted down since the panel is no longer there and the window is split down
1. The mouse, which hasn't moved, is now back in the area of line 1
1. This makes the selection cursor move back to line 1, causing the panel to show again
1. Go back to step 2.

**Comment by gkrawiec** [comment] 2015-08-12 19:19
is it possible to disable the panel from showing up until the mouse button is released instead of immediately after its pressed (or disable it during drag?).

**Comment by gkrawiec** [comment] 2015-08-13 22:35
shouldnt this be reopened now that it has been reproduced?

**Comment by Arcanemagus** [comment] 2015-08-13 22:40
I would say so, but have no rights here. @steelbrain any thoughts on how to solve this issue? I rather like the idea of not updating the panel contents while dragging the mouse.

**Comment by gkrawiec** [comment] 2015-08-17 21:03
@steelbrain Is this not considered a bug or has not reopening the issue just been an oversight?

**Comment by steelbrain** [comment] 2015-08-17 21:05
@gkrawiec sorry man, but that's how atom panels work. It would be quite complicated to achieve this, besides if we solve this in linter, all the other packages would still have this problem. I would suggest you try suggesting this to the core guys in atom repo.

**Comment by steelbrain** [comment] 2015-08-17 21:06
@gkrawiec As a workaround, You can disable `lintOnFly`, then the panel would only update on save.

**Comment by gkrawiec** [comment] 2015-08-17 21:10
I find the linting very useful as I am currently learning. It gives me immediate feedback on simple errors.

Would it be possible to not update the bottom linter panel during the drag event? (which is when this bug shows up)

**Comment by Arcanemagus** [comment] 2015-08-17 21:12
@steelbrain disabling `lintOnFly` wouldn't affect this, as the editor contents and results of the linter are not changing, only the display.

**Comment by steelbrain** [comment] 2015-08-17 21:15
@Arcanemagus We are updating the message registry 10 (or maybe 5?) times a second, and every time the registry is updated and a change is detected, we fired the change event and the panel updates instantly. To workaround this we would have to implement the panel updates independent of the message registry, besides, I have been working for ~250 errors for the last few weeks and I **never** encountered this error, disabling `lintOnFly` sounds like a fair tradeoff to me :)

**Comment by Arcanemagus** [comment] 2015-08-17 21:20
`lintOnFly` has nothing to do with this though. No changes are being made to the messages, no editor content is changing.

The _only_ thing that is changing is the line the cursor is currently on. Since the error display mode is set to `Line` (instead of `File` or `Project`), the _displayed_ messages change based on where your cursor is, but nothing is changing the actual messages.

**Comment by gkrawiec** [comment] 2015-08-17 21:25
I just tested disabling Lint On Fly. It doesnt really fix it. It works fine until a save. Then, the error panel pops up....and once the error is already in the panel, if I click and drag from the line, the bouncy effect starts again.

**Comment by steelbrain** [comment] 2015-08-17 21:26
Right, we could update once all are done but that would mean that if one of your linters is lazy, You won't see result from any.

**Comment by gkrawiec** [comment] 2015-08-17 22:27
@steelbrain , I just tested the combinations of "lint on fly" and "lint on save". The problem is the same with all combinations, so its not a workaround. Do you have any other suggestions for things I can try?

**Comment by steelbrain** [comment] 2015-08-17 22:29
@gkrawiec Your target is in https://github.com/atom-community/linter/blob/master/lib/linter-registry.coffee#L42-L53
Ping me in about 10 hours and I'll make a patch for you. Maybe make it an option soon.

**Comment by gkrawiec** [comment] 2015-08-18 23:46
Hi @steelbrain , did you get a chance to look into this? If you want me to test stuff let me know.
thanks!

**Comment by steelbrain** [comment] 2015-08-20 18:07
@gkrawiec sorry been **very** busy. I am working on a PR to make this an option in the next release.

**Comment by gkrawiec** [comment] 2015-08-20 18:09
@steelbrain thank you! very much appreciated.

**Comment by steelbrain** [comment] 2015-08-20 19:04
@gkrawiec A fix is up in https://github.com/atom-community/linter/pull/862
I'll be merging it soon after adding some specs

**Closed** 2015-08-20 20:02 UTC
Labels: feature request, in progress, priority-medium, ui

**Comment by gkrawiec** [comment] 2015-08-21 16:37
@steelbrain I just updated to to the new master, and now have the "Update messages when all providers are done" checked. The jumping window behavior is still there.
Here are my settings 
https://www.dropbox.com/s/vvwi7sgaq0tsqik/Screenshot%202015-08-21%2009.35.53.png?dl=0
Is there anything else I have to check or uncheck for this to work?
thanks!

**Comment by steelbrain** [comment] 2015-08-21 22:18
Nooooooo :sob: 
Are you able to repro this on someone else's computer or another OS? Maybe your xlib or something has a bug?

**Comment by gkrawiec** [comment] 2015-08-21 22:22
@Arcanemagus Can you please test the new linter version and see if you still reproduce the bug when the activating the  "Update messages when all providers are done" option?
thanks.

**Comment by steelbrain** [comment] 2015-08-21 22:25
@gkrawiec alternatively If you want the panel to go smooth, select the file tab of the bottom panel and enable that option. That should work well I think.

**Comment by gkrawiec** [comment] 2015-08-21 23:30
@steelbrain I tried that, but 1) i always have too many errors so it takes a large chunk of the panel, and 2) Its much harder to see which error belongs where

if its not fixable, I can live with it, (but remove the code, since it doesnt seem to be doing anything). Let me know what you decide to do. Lets see if @Arcanemagus can reproduce it first though. I have nowhere else to test it. 

thanks.

**Comment by steelbrain** [comment] 2015-08-21 23:32
You might wanna subscribe to this for the belonging part https://github.com/atom-community/linter/issues/865
