### ISSUE TITLE
Failed to activate the linter package (redux)

### ISSUE THREAD

**Issue by Luckz** [atom-community/linter#942] opened 2015-10-08 09:33 UTC
https://github.com/atom-community/linter/issues/882
was closed referring to a *Windows-only* bug affecting users with special characters in their user names.

That this is incorrect anybody can see who actually read the last complaints there about 'grim' not being found on Linux systems too (which happened for me too on Windows when updating a month-old linter to the current version). This issue is unrelated to https://github.com/atom/atom/issues/8891 .

**Comment by steelbrain** [comment] 2015-10-08 09:34
So your issue is that `grim` not found one? Restart and it should be fixed.

**Comment by marksherman** [comment] 2015-10-08 13:11
Can confirm: bug appeared on Mac OS, and was fixed by a restart. On restart the package was updated.

**Comment by ezfe** [comment] 2015-10-08 21:16
Fixed on restart here (OS X)

**Comment by tbenade** [comment] 2015-10-09 02:50
+1

**Comment by fernandosantucci** [comment] 2015-10-09 06:29
The bug is confirmed on Ubuntu 14.04 LTS.

**Comment by NM-** [comment] 2015-10-09 11:46
Error: Cannot find module 'grim'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.module.exports.activate (/Users/neco/.atom/packages/linter/lib/main.coffee:65:19)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:243:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:224:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:216:14)

**Comment by steelbrain** [comment] 2015-10-09 11:59
@NM- did a restart fix it?

**Comment by josegonzalez** [comment] 2015-10-10 03:53
Restart fixed it for me.

**Comment by iggyvolz** [comment] 2015-10-12 01:03
Can also confirm on OS X 10.9, and a restart of Atom fixed it.

**Comment by basarat** [comment] 2015-10-12 04:44
I am on windows.

**Fix:** Restart atom after update. 

Definitely seems like an atom bug.

**Comment by benechols-wf** [comment] 2015-10-13 16:29
I am on ubuntu 15.04 using latest atom and linter and keep getting this on every restart:

TypeError: undefined is not a function
    at EditorLinter.addGutter (/home/ben/.atom/packages/linter/lib/editor-linter.js:106:33)
    at EditorLinter.handleGutter (/home/ben/.atom/packages/linter/lib/editor-linter.js:99:14)
    at /home/ben/.atom/packages/linter/lib/editor-linter.js:50:13
    at Config.module.exports.Config.observeKeyPath (/usr/share/atom/resources/app.asar/src/config.js:555:7)
    at Config.module.exports.Config.observe (/usr/share/atom/resources/app.asar/src/config.js:135:21)
    at new EditorLinter (/home/ben/.atom/packages/linter/lib/editor-linter.js:48:40)
    at EditorRegistry.create (/home/ben/.atom/packages/linter/lib/editor-registry.coffee:19:22)
    at Linter.createEditorLinter (/home/ben/.atom/packages/linter/lib/linter.coffee:122:35)
    at /home/ben/.atom/packages/linter/lib/linter.coffee:53:24
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:266:9)

**Comment by Arcanemagus** [comment] 2015-10-13 16:42
@benechols-wf that looks like a completely different issue from the stack trace. Can you ensure you are running the latest Atom, and if so but you are still seeing that file a new issue to troubleshoot that?

**Comment by CoreySwish** [comment] 2015-10-14 04:10
[Enter steps to reproduce below:]

1. updated package


**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.8.1


### Stack Trace

Failed to activate the linter package

```
At Cannot find module 'grim'

Error: Cannot find module 'grim'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Users/coreybeaumont/Downloads/Atom 2.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.module.exports.activate (/Users/coreybeaumont/.atom/packages/linter/lib/main.coffee:61:15)
  at Package.module.exports.Package.activateNow (/Users/coreybeaumont/Downloads/Atom 2.app/Contents/Resources/app.asar/src/package.js:243:19)
  at /Users/coreybeaumont/Downloads/Atom 2.app/Contents/Resources/app.asar/src/package.js:224:30
  at Package.module.exports.Package.measure (/Users/coreybeaumont/Downloads/Atom 2.app/Contents/Resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Users/coreybeaumont/Downloads/Atom 2.app/Contents/Resources/app.asar/src/package.js:216:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Users/coreybeaumont/Downloads/Atom 2.app/Contents/Resources/app.asar/src/package-manager.js:486:21)
  at /Users/coreybeaumont/Downloads/Atom 2.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:313:60
  at exit (/Users/coreybeaumont/Downloads/Atom 2.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:60:16)
  at triggerExitCallback (/Users/coreybeaumont/Downloads/Atom 2.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Users/coreybeaumont/Downloads/Atom 2.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/Users/coreybeaumont/Downloads/Atom 2.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -0:25.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -0:23.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
emmet, v2.3.13
linter, v1.8.1
linter-bootlint, v0.0.6
linter-csslint, v1.1.0
linter-jshint, v1.2.1
linter-jsonlint, v1.0.1
linter-php, v1.0.5
minimap, v4.13.4

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2015-10-14 09:50
For all the future people on here. Restart your atom and it'll be fixed. It's an atom bug. Kinda related atom/atom#8891

**Closed by steelbrain** 2015-10-14 09:50 UTC
