### ISSUE TITLE
Uncaught TypeError: Invalid Point: (4, NaN)

### ISSUE THREAD

**Issue by tvandervorm** [atom-community/linter#1060] opened 2016-01-31 06:11 UTC
With this snippet:

```html
<div>
    ... some html here ...
</div>
<script>
    $('div').html('').append($('<a style="color:red" href="<?php echo $this->url('url_name'); ?>">link text</a>'))
                     .append($('<div></div>'));
</script>
```

As soon as I modify anything in the script block (specifically the href) I get the error below.
In order to get linting working again, I have to restart Atom.

Point of note is that I'm using both linter-php and linter-jshint, seeing as the line contains both js and php, this might be a conflict between those two?

**Atom Version**: 1.4.1
**System**: "Fedora release
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.3

### Stack Trace

Uncaught TypeError: Invalid Point: (4, NaN)

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/point.js:63

TypeError: Invalid Point: (4, NaN)
    at Function.module.exports.Point.assertValid (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1015:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1003:20)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:204:46)
    at TextEditorMarkerLayer.module.exports.TextEditorMarkerLayer.markBufferRange (/usr/share/atom/resources/app.asar/src/text-editor-marker-layer.js:78:52)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/usr/share/atom/resources/app.asar/src/display-buffer.js:1100:38)
    at TextEditor.module.exports.TextEditor.markBufferRange (/usr/share/atom/resources/app.asar/src/text-editor.js:1339:59)
    at /home/tvandervorm/.atom/packages/linter/lib/editor-linter.js:50:34
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at EditorLinter.addMessage (/home/tvandervorm/.atom/packages/linter/lib/editor-linter.js:137:20)
    at /home/tvandervorm/.atom/packages/linter/lib/linter-views.js:104:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (/home/tvandervorm/.atom/packages/linter/lib/linter-views.js:102:11)
    at LinterViews.render (/home/tvandervorm/.atom/packages/linter/lib/linter-views.js:59:10)
    at /home/tvandervorm/.atom/packages/linter/lib/linter.coffee:70:30
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at MessageRegistry.updatePublic (/home/tvandervorm/.atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (/home/tvandervorm/.atom/packages/linter/lib/message-registry.js:24:16)
```

### Commands

```
     -0:01.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "metrics",
      "deprecation-cop"
    ],
    "excludeVcsIgnoredPaths": false,
    "ignoredNames": [
      "portal/library/*",
      ".git"
    ],
    "projectHome": "/srv/sites",
    "themes": [
      "one-dark-ui",
      "graveyard-soda-syntax"
    ]
  },
  "linter": {
    "errorPanelHeight": 393
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.1.1
docblockr, v0.7.3
graveyard-soda-syntax, v0.0.0
linter, v1.11.3
linter-jshint, v1.2.2
linter-php, v1.1.7
minimap, v4.19.0
pigments, v0.22.1
project-manager, v2.7.5

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2016-01-31 12:36
@Arcanemagus That code block above looks js, do you think it could be the same esprima bug?

**Comment by tvandervorm** [comment] 2016-01-31 21:00
Been browsing through the closed issues a bit, and read this one: https://github.com/jquery/esprima/issues/1457, and seems to me that is indeed the case, meaning this is not a linter issue but a linter-jshint issue.

However, seeing as linting completely stops after this bug occurs (restart of atom required), perhaps the core linter package could be made a bit more robust? i.e. show the error, but be able to continue after that? 

Haven't done any atom package development myself, so don't know how easy/hard this is, but having to restart after almost every file that contains a mix of html/php/js gets tiresome fast..

**Comment by Arcanemagus** [comment] 2016-02-01 05:50
You shouldn't need to restart Atom to get linting to work again... it will happily complain at you all day long that there is an error :stuck_out_tongue: (which gets annoying...)

If it's locking up that _might_ be a bug with `linter-jshint`, but I'm not sure how.

**Comment by steelbrain** [comment] 2016-02-05 16:41
Dupe of #1048 #1053 #1058 #1059 #1061 #1062 #1065 #1068

**Closed by steelbrain** 2016-02-05 16:41 UTC
Labels: external
