### ISSUE TITLE
Uncaught TypeError: Invalid Point: (21, NaN)

### ISSUE THREAD

**Issue by junqdu** [atom-community/linter#1076] opened 2016-02-09 23:52 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.0
**System**: Mac OS X 10.10.5
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.3

### Stack Trace

Uncaught TypeError: Invalid Point: (21, NaN)

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63

TypeError: Invalid Point: (21, NaN)
    at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1015:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1003:20)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:204:46)
    at TextEditorMarkerLayer.module.exports.TextEditorMarkerLayer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker-layer.js:78:52)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1103:38)
    at TextEditor.module.exports.TextEditor.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1367:59)
    at /Users/jdu/.atom/packages/linter/lib/editor-linter.js:50:34
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at EditorLinter.addMessage (/Users/jdu/.atom/packages/linter/lib/editor-linter.js:137:20)
    at /Users/jdu/.atom/packages/linter/lib/linter-views.js:104:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (/Users/jdu/.atom/packages/linter/lib/linter-views.js:102:11)
    at LinterViews.render (/Users/jdu/.atom/packages/linter/lib/linter-views.js:59:10)
    at /Users/jdu/.atom/packages/linter/lib/linter.coffee:39:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at MessageRegistry.updatePublic (/Users/jdu/.atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (/Users/jdu/.atom/packages/linter/lib/message-registry.js:24:16)
```

### Commands

```
  7x -1:12.8.0 core:select-right (atom-text-editor.editor.is-focused)
     -1:07.6.0 core:copy (atom-text-editor.editor.is-focused)
     -1:05.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:04.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:04.4.0 core:paste (atom-text-editor.editor.is-focused)
  2x -1:03.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:01.2.0 core:paste (atom-text-editor.editor.is-focused)
     -1:00.3.0 core:undo (atom-text-editor.editor.is-focused)
     -0:59.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:58.9.0 core:paste (atom-text-editor.editor.is-focused)
  3x -0:58.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:50.3.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:45.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:45.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:44.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:41 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "linter": {
    "errorPanelHeight": 110
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.22
highlight-selected, v0.11.2
linter, v1.11.3
linter-jshint, v1.3.0
minimap, v4.19.0
seti-syntax, v0.4.1
seti-ui, v0.8.1
tabs-to-spaces, v1.0.1

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2016-02-09 23:53
Dupe of #1048 #1053 #1058 #1059 #1061 #1062 #1065 #1068 #1060 #1063 #1064 #1066  #1069 #1070 #1071 #1072 #1074

**Closed by steelbrain** 2016-02-09 23:53 UTC

**Comment by Arcanemagus** [comment] 2016-02-10 00:10
I think it's time that we put in a workaround in jshint, at least until the current crop of bugs in there and `esprima` are fixed...

**Comment by steelbrain** [comment] 2016-02-10 00:11
@Arcanemagus What kinda workaround do you have in mind?
