### ISSUE TITLE
Failed to activate the linter package - cannot find module 'xregexp'

### ISSUE THREAD

**Issue by adrianovieira** [atom-community/linter#810] opened 2015-08-05 20:34 UTC
[Enter steps to reproduce below:]

1. Just open Atom 
1. the message pops-up

**Atom Version**: 1.0.2
**System**: "Fedora release
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.3.0

### Stack Trace

Failed to activate the linter package

```
At Cannot find module 'xregexp'

Error: Cannot find module 'xregexp'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/users/adriano.vieira/.atom/packages/linter/lib/helpers.coffee:2:11)
  at Object.<anonymous> (/home/users/adriano.vieira/.atom/packages/linter/lib/helpers.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/users/adriano.vieira/.atom/packages/linter/lib/linter-plus.coffee:5:11)
  at Object.<anonymous> (/home/users/adriano.vieira/.atom/packages/linter/lib/linter-plus.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.module.exports.activate (/home/users/adriano.vieira/.atom/packages/linter/lib/main.coffee:48:18)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:240:19)
  at /usr/share/atom/resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:452:21)
  at /usr/share/atom/resources/app.asar/src/package-manager.js:436:29
  at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:311:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:431:19)
  at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:412:46)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom.js:645:21)
  at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:96:23)
  at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:36:7)

```

### Commands

```
```

### Config

```json
{
  "core": {},
  "linter": {}
}
```

### Installed Packages

```coffee
# User
linter, v1.3.0
linter-erb, v0.1.1
linter-puppet-lint, v0.2.9

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2015-08-05 20:36
Repro steps please? Did you install any of those packages using git? and forgot to do `apm install` in their dirs?

**Comment by adrianovieira** [comment] 2015-08-05 22:12
I just the installation problem.

We're behind a proxy...
I configure the proxy var at ```.atom/.apmrc``` with ```https-proxy = http://<user:pass>@<proxy:port>```
 but **```apm```** appear not authenticate a proxy with digest authentication.

**Comment by steelbrain** [comment] 2015-08-09 20:44
If `apm` doesn't support that, I can only hope npm does, You can also do `npm install` to achieve the same thing. Closing for now, but feel free to continue the discussion.

**Closed by steelbrain** 2015-08-09 20:44 UTC

**Comment by xiegeo** [comment] 2015-08-27 01:29
Posting here because the View Issue button in atom says this issue has already been reported links to this page. Maybe someone could look into that too.

[Enter steps to reproduce below:]

0. First time using atom since upgrading to win10
1. Clicked on update all
2. Wait for update to process

**Atom Version**: 1.0.7
**System**: Microsoft Windows 10 Home
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.4.3


### Stack Trace

Failed to activate the linter package

```
At undefined is not a function

TypeError: undefined is not a function
  at new Linter (C:\Users\George\.atom\packages\linter\lib\linter.coffee:34:54)
  at Object.module.exports.activate (C:\Users\George\.atom\packages\linter\lib\main.coffee:54:21)
  at Package.module.exports.Package.activateNow (C:\Users\George\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:243:19)
  at C:\Users\George\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:224:30
  at Package.module.exports.Package.measure (C:\Users\George\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:167:15)
  at Package.module.exports.Package.activate (C:\Users\George\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:216:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\George\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package-manager.js:486:21)
  at C:\Users\George\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\settings-view\lib\package-manager.js:312:60
  at exit (C:\Users\George\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\settings-view\lib\package-manager.js:59:16)
  at triggerExitCallback (C:\Users\George\AppData\Local\atom\app-1.0.7\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\George\AppData\Local\atom\app-1.0.7\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
 10x -9:15.4.0 core:backspace (atom-text-editor.editor.is-focused)
 18x -8:27 core:move-left (atom-text-editor.editor.is-focused)
     -8:24.9.0 editor:newline (atom-text-editor.editor.is-focused)
 22x -8:24.4.0 core:move-right (atom-text-editor.editor.is-focused)
 14x -8:11.9.0 core:move-left (atom-text-editor.editor.is-focused)
     -8:10.8.0 core:move-up (atom-text-editor.editor.is-focused)
 22x -8:10.3.0 core:move-right (atom-text-editor.editor.is-focused)
 14x -8:08.0 core:move-left (atom-text-editor.editor.is-focused)
 15x -8:06.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -8:04.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -8:00.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:58.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -7:55.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -7:54.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:23.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:21.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {},
  "linter": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
language-protobuf, v0.5.0
linter, v1.4.3

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2015-08-27 01:30
@xiegeo remove and re-install linter

**Comment by xiegeo** [comment] 2015-08-27 01:42
Just restarting atom worked, I think, no more errors. Is there a good way to report non-critical / temporary errors?

**Comment by steelbrain** [comment] 2015-08-27 17:47
@xiegeo well, atom's the one who handles that, so not sure about that.

**Comment by Arcanemagus** [comment] 2015-08-27 18:25
Also @xiegeo according to that package list you have no `linter-*` providers installed, so `linter` won't be doing too much for you :wink:.

**Comment by jeffmcmahan** [comment] 2015-09-11 18:09
I've been getting this error for a while on Yosemite; the stack is identical to @xiegeo's. Win8 is apparently not a critical factor.

@Arcanemagus, you should start by granting the reasonable assumption that @xiegeo removed providers in an attempt to identify a provider as a source of the problem.

**Comment by steelbrain** [comment] 2015-09-11 18:13
@jeffmcmahan It's been ages since this error has been fixed. We've even completely removed `xregexp` usage and all from this repo. so If you're still getting this error you might wanna have a fresh start with your `~/.atom`.

**Comment by Arcanemagus** [comment] 2015-09-11 18:18
Also @jeffmcmahan you would not believe the number of people filing issues saying it doesn't work who either don't have any `linter-*` packages installed, or don't have `linter` installed but have a `linter-*` package installed (this is now fixable, and providers are updating for this).

Sometimes pointing out what seems obvious helps somebody who is looking at it from a different perspective and can't see that. In the worst case it doesn't hurt anything.
