### ISSUE TITLE
Failed to activate the linter package

### ISSUE THREAD

**Issue by chenlianjiang** [atom-community/linter#1031] opened 2015-12-17 02:11 UTC
**Atom Version**: 1.3.1
**System**: Windows 7
**Thrown From**: linter package, v1.11.3
```
Cannot find module 'interact.js'
```

## Hide Stack Trace
```
Error: Cannot find module 'interact.js'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\Administrator\AppData\Local\atom\app-1.3.1\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.3.1\resources\app.asar\src\native-compile-cache.js:41:21)
    at Object.<anonymous> (C:/Users/Administrator/.atom/packages/linter/lib/ui/bottom-panel.js:3:18)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.3.1\resources\app.asar\src\native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.3.1\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.3.1\resources\app.asar\src\native-compile-cache.js:41:21)
    at Object.<anonymous> (C:/Users/Administrator/.atom/packages/linter/lib/linter-views.js:3:50)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.3.1\resources\app.asar\src\native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.3.1\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.3.1\resources\app.asar\src\native-compile-cache.js:41:21)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/linter/lib/linter.coffee:3:15)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/linter/lib/linter.coffee:1:1)
    at Module._compile (C:\Users\Administrator\AppData\Local\atom\app-1.3.1\resources\app.asar\src\native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Administrator\AppData\Local\atom\app-1.3.1\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Administrator\AppData\Local\atom\app-1.3.1\resources\app.asar\src\native-compile-cache.js:41:21)
    at Object.module.exports.activate (file:///C:/Users/Administrator/.atom/packages/linter/lib/main.coffee:130:18)
    at Package.module.exports.Package.activateNow (C:\Users\Administrator\AppData\Local\atom\app-1.3.1\resources\app.asar\src\package.js:170:19)
    at C:\Users\Administrator\AppData\Local\atom\app-1.3.1\resources\app.asar\src\package.js:150:32
    at Package.module.exports.Package.measure (C:\Users\Administrator\AppData\Local\atom\app-1.3.1\resources\app.asar\src\package.js:92:15)
    at C:\Users\Administrator\AppData\Local\atom\app-1.3.1\resources\app.asar\src\package.js:143:26
    at Package.module.exports.Package.activate (C:\Users\Administrator\AppData\Local\atom\app-1.3.1\resources\app.asar\src\package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Administrator\AppData\Local\atom\app-1.3.1\resources\app.asar\src\package-manager.js:517:21)
    at C:\Users\Administrator\AppData\Local\atom\app-1.3.1\resources\app.asar\src\package-manager.js:499:29
    at Config.module.exports.Config.transactAsync (C:\Users\Administrator\AppData\Local\atom\app-1.3.1\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\Administrator\AppData\Local\atom\app-1.3.1\resources\app.asar\src\package-manager.js:494:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\Administrator\AppData\Local\atom\app-1.3.1\resources\app.asar\src\package-manager.js:478:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (C:\Users\Administrator\AppData\Local\atom\app-1.3.1\resources\app.asar\src\atom-environment.js:686:21)
    at module.exports (C:\Users\Administrator\AppData\Local\atom\app-1.3.1\resources\app.asar\src\initialize-application-window.js:28:10)
    at setupWindow (file:///C:/Users/Administrator/AppData/Local/atom/app-1.3.1/resources/app.asar/static/index.js:85:5)
    at window.onload (file:///C:/Users/Administrator/AppData/Local/atom/app-1.3.1/resources/app.asar/static/index.js:40:9)
```

**Comment by Arcanemagus** [comment] 2015-12-17 08:20
Can you try reinstalling `linter`? Sometimes Atom doesn't fully install all dependencies.

**Comment by Tipyx** [comment] 2015-12-22 21:53
Ahoy o/ !
I have not exactly the same issue with linter 1.11.3, but it redirect me on this page :)

```
cannot find module 'grim'
```

And even after reinstall many times :/

The stack :

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.3


### Stack Trace

Failed to activate the linter package

```
At Cannot find module 'grim'

Error: Cannot find module 'grim'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.module.exports.activate (/Users/Tipyx/.atom/packages/linter/lib/main.coffee:76:5)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:232:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:212:32
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:205:26
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```

### Commands

```
     -6:33.3.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -6:29.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -6:28.1.0 core:move-up (atom-text-editor.editor.mini.is-focused)
 10x -6:26.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:50.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.19.0
color-picker, v2.0.13
haxe, v0.8.10
language-haxe, v0.3.0
linter, v1.11.3
monokai, v0.18.0

# Dev
No dev packages
```

**Comment by mirzu** [comment] 2015-12-29 16:54
Got the same error and tried to reinstall with no luck.

**Comment by steelbrain** [comment] 2015-12-29 16:55
@mirzu This error can occur for a lot of reasons, can you post your stack trace?

**Comment by mirzu** [comment] 2015-12-29 19:40
```
Error: Cannot find module 'grim'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.activate (/Users/mirzu/.atom/packages/linter/lib/main.coffee:76:19)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:517:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by Arcanemagus** [comment] 2015-12-29 19:49
@mirzu Can you go to `/Users/mirzu/.atom/packages/linter/` in a terminal and run `apm install` with Atom closed? That should verify all the dependencies are installed.

**Comment by Arcanemagus** [comment] 2015-12-29 19:51
I'm marking this as closed btw since this is an issue with Atom not properly installing the package and not `linter` itself, please continue discussing though :wink:.

**Closed by Arcanemagus** 2015-12-29 19:51 UTC

**Comment by ericgundrum** [comment] 2016-01-08 22:08
I encountered the same problem on OSX. Following the suggestion by @Arcanemagus, I quit Atom, then in Terminal, `cd ~/.atom/packages/linter`, followed by `<apm> install` where `<apm>` is the full path to `Atom.app/Contents/Resources/app/apm/bin/apm`. (Apparently I don't have Atom cli tools installed -- I don't seem to miss them.) This showed the result `Installing modules ✓`, which seemed too vague to me. Just in case nothing useful happened, I then tried `<apm> install linter` with the result `Installing linter to ~/.atom/packages ✓`. 

When I restarted Atom, linter was working. Unfortunately I cannot say which command fixed it.

**Comment by Arcanemagus** [comment] 2016-01-08 22:40
Although they both should have done the same thing, it not working in the first place is what got you here so it's impossible to tell. Glad to hear you got it working again!

**Comment by formula1** [comment] 2016-01-08 23:25
Atom sent me to this issue for the following stacktrace

```
/home/sam/.atom/packages/linter/lib/ui/bottom-status.js:3
class BottomStatus extends HTMLElement{
^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:75:16)
    at Module._compile (module.js:458:25)
    at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/home/sam/.atom/packages/linter/lib/ui/bottom-container.js:20:36)
    at Module._compile (module.js:475:26)
    at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:166:19)
```

Looking at the version

```
apm  0.149.0
npm  2.5.1
node 0.10.35
python 2.7.6
git 1.9.1
```

I currently have 5.4.0 installed (via n) so I'm a little confused why atom uses 0.10.35. Perhaps it installs it? I've attempted to uninstall and reinstall atom multiple times but it seems as though it doesn't want to use 5.4.0. I'm assuming Linter uses babel however it is not within the package.json. Is atom doing something wrong?

**Comment by Arcanemagus** [comment] 2016-01-09 00:13
That version is from `apm -v` and is showing the embedded `npm` that `apm` wraps around. You can't update that.

That being said, that version of `apm` is quite old, it looks like you need to update your Atom installation. (I'm guessing you are on such an old version it doesn't even have `class` support in its JS interpreter.

**Comment by formula1** [comment] 2016-01-09 02:04
AH, I'm a fool. I had .debs available and was installing the old one. Thanks for making me double check

**Comment by Arcanemagus** [comment] 2016-01-09 06:24
I'm just glad it was something simple like that :wink:.

**Comment by reinaldomendes** [comment] 2016-02-15 18:32
TypeError: undefined is not a function
  at EditorLinter.addGutter (/home/reinaldo/.atom/packages/linter/lib/editor-linter.js:134:35)
  at EditorLinter.handleGutter (/home/reinaldo/.atom/packages/linter/lib/editor-linter.js:127:16)
  at /home/reinaldo/.atom/packages/linter/lib/editor-linter.js:57:13
  at Config.module.exports.Config.observeKeyPath (/usr/share/atom/resources/app/src/config.js:540:7)
  at Config.module.exports.Config.observe (/usr/share/atom/resources/app/src/config.js:122:21)
  at new EditorLinter (/home/reinaldo/.atom/packages/linter/lib/editor-linter.js:55:40)
  at EditorRegistry.create (/home/reinaldo/.atom/packages/linter/lib/editor-registry.js:30:28)
  at Linter.createEditorLinter (/home/reinaldo/.atom/packages/linter/lib/linter.coffee:94:29)
  at /home/reinaldo/.atom/packages/linter/lib/linter.coffee:48:71
  at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app/src/workspace.js:266:9)
  at new Linter (/home/reinaldo/.atom/packages/linter/lib/linter.coffee:48:39)
  at Object.module.exports.activate (/home/reinaldo/.atom/packages/linter/lib/main.coffee:131:21)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:222:19)
  at /usr/share/atom/resources/app/src/package.js:203:30
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:147:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:195:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:434:21)
  at /usr/share/atom/resources/app/src/package-manager.js:303:19
  at /usr/share/atom/resources/app/src/config.js:559:20
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app/src/config.js:721:29)
  at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app/src/config.js:536:19)
  at Config.module.exports.Config.set (/usr/share/atom/resources/app/src/config.js:220:14)
  at Config.module.exports.Config.removeAtKeyPath (/usr/share/atom/resources/app/src/config.js:330:12)
  at Package.module.exports.Package.enable (/usr/share/atom/resources/app/src/package.js:132:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/usr/share/atom/resources/app/src/package-manager.js:132:14)
  at HTMLButtonElement.<anonymous> (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:213:27)
  at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4116:28)




----------------------------------------------------


user@local $ apm -v 
apm  0.157.0
npm  2.5.1
node 0.10.35
python 2.7.6
git 1.9.1

**Comment by steelbrain** [comment] 2016-02-15 18:33
@reinaldomendes You need to upgrade your Atom, it's very old
