### ISSUE TITLE
Uncaught TypeError: Invalid Point: (74, NaN)

### ISSUE THREAD

**Issue by gosselin-tactill** [atom-community/linter#1063] opened 2016-02-02 14:40 UTC
[Enter steps to reproduce below:]

1. Just open a file

**Atom Version**: 1.4.2
**System**: Mac OS X 10.11.3
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.3

### Stack Trace

Uncaught TypeError: Invalid Point: (74, NaN)

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63

TypeError: Invalid Point: (74, NaN)
    at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1015:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1003:20)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:204:46)
    at TextEditorMarkerLayer.module.exports.TextEditorMarkerLayer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker-layer.js:78:52)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1100:38)
    at TextEditor.module.exports.TextEditor.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1339:59)
    at /Users/gossel_j/.atom/packages/linter/lib/editor-linter.js:50:34
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at EditorLinter.addMessage (/Users/gossel_j/.atom/packages/linter/lib/editor-linter.js:137:20)
    at /Users/gossel_j/.atom/packages/linter/lib/linter-views.js:104:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (/Users/gossel_j/.atom/packages/linter/lib/linter-views.js:102:11)
    at LinterViews.render (/Users/gossel_j/.atom/packages/linter/lib/linter-views.js:59:10)
    at /Users/gossel_j/.atom/packages/linter/lib/linter.coffee:39:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at MessageRegistry.updatePublic (/Users/gossel_j/.atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (/Users/gossel_j/.atom/packages/linter/lib/message-registry.js:24:16)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "linter": {
    "showErrorPanel": false
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-ternjs, v0.13.2
autocomplete-modules, v1.3.1
color-picker, v2.1.1
compare-files, v0.6.2
file-icons, v1.6.14
language-nginx, v0.6.1
language-svg, v0.9.0
linter, v1.11.3
linter-eslint, v6.0.0
linter-jshint, v1.3.0
pigments, v0.22.1
project-manager, v2.7.5
react, v0.14.1

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment] 2016-02-03 19:23
This is almost certainly a bug in the `esprima` parser used by `jshint`. If you want us to verify that you'll need to send the file you were seeing this on somewhere we can access it, but it's unlikely this is necessary.

You might want to look into moving to a linter that supports alternative parsers like `eslint` or `jscs`.

**Comment by steelbrain** [comment] 2016-02-05 16:41
Dupe of #1048 #1053 #1058 #1059 #1061 #1062 #1065 #1068 #1060

**Closed by steelbrain** 2016-02-05 16:41 UTC
Labels: external
