### ISSUE TITLE
Uncaught TypeError: Invalid Point: (NaN, 0)

### ISSUE THREAD

**Issue by beckybair** [atom-community/linter#1058] opened 2016-01-26 02:10 UTC
[Enter steps to reproduce below:]

1. opened Atom to work on Ruby file
2. opened my users_controller.rb which I suspect to have errors
3. this error pops up and on the bottom status line it shows 12 errors in the file - the file does not show where the errors are though.

**Atom Version**: 1.4.1
**System**: Microsoft Windows 10 Home
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.3

### Stack Trace

Uncaught TypeError: Invalid Point: (NaN, 0)

```
At C:\Users\Becky\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\text-buffer\lib\point.js:63

TypeError: Invalid Point: (NaN, 0)
    at Function.module.exports.Point.assertValid (C:\Users\Becky\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\text-buffer\lib\point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (C:\Users\Becky\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1015:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (C:\Users\Becky\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1003:20)
    at MarkerLayer.module.exports.MarkerLayer.markRange (C:\Users\Becky\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\text-buffer\lib\marker-layer.js:204:46)
    at TextEditorMarkerLayer.module.exports.TextEditorMarkerLayer.markBufferRange (C:\Users\Becky\AppData\Local\atom\app-1.4.1\resources\app.asar\src\text-editor-marker-layer.js:78:52)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (C:\Users\Becky\AppData\Local\atom\app-1.4.1\resources\app.asar\src\display-buffer.js:1100:38)
    at TextEditor.module.exports.TextEditor.markBufferRange (C:\Users\Becky\AppData\Local\atom\app-1.4.1\resources\app.asar\src\text-editor.js:1339:59)
    at C:/Users/Becky/.atom/packages/linter/lib/editor-linter.js:50:34
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Becky\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Becky\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at EditorLinter.addMessage (C:/Users/Becky/.atom/packages/linter/lib/editor-linter.js:137:20)
    at C:/Users/Becky/.atom/packages/linter/lib/linter-views.js:104:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (C:/Users/Becky/.atom/packages/linter/lib/linter-views.js:102:11)
    at LinterViews.render (C:/Users/Becky/.atom/packages/linter/lib/linter-views.js:59:10)
    at file:///C:/Users/Becky/.atom/packages/linter/lib/linter.coffee:39:14
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Becky\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Becky\AppData\Local\atom\app-1.4.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at MessageRegistry.updatePublic (C:/Users/Becky/.atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (C:/Users/Becky/.atom/packages/linter/lib/message-registry.js:24:16)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "linter": {
    "showErrorPanel": false
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.1.0
emmet, v2.4.1
jshint, v1.8.3
linter, v1.11.3
linter-erb, v1.0.0
linter-rails-best-practices, v0.2.2
linter-ruby, v1.2.1
linter-ruby-reek, v1.3.0
minimap-find-and-replace, v4.4.0
pigments, v0.21.0
wakatime, v5.0.2

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment] 2016-01-27 06:05
Do you know what file you were editing when you hit this error?
Are you able to share it or can you create a minimal test case that reproduces it?
Do you know which linter plugin was active on that file?

**Comment by beckybair** [comment] 2016-01-27 15:14
It was in my:  users_controller.rb file - you can see it here:  https://github.com/beckybair/rails-pinning-app/blob/master/app/controllers/users_controller.rb

I'm new to Linter so if you can tell me how to know which linter plugin is active I can let you know.  I know I installed several different linter packages - which are all listed above in the installed packages list.  Sorry I'm not able to give you more information.  

Anything else you need, just let me know...

**Comment by Arcanemagus** [comment] 2016-01-27 17:50
Looks like this is caused by bad parsing of `reek` output by `linter-ruby-reek`, is there any reason you aren't using [linter-reek](https://github.com/AtomLinter/linter-reek)?

![image](https://cloud.githubusercontent.com/assets/427137/12622654/43fe5c3e-c4db-11e5-9bdc-3a37bb15858d.png)

**Comment by Arcanemagus** [comment] 2016-01-27 17:58
Marking this as closed since this isn't an issue with `linter`, feel free to keep the discussion going though :wink:.

**Closed by Arcanemagus** 2016-01-27 17:58 UTC
Labels: external

**Comment by beckybair** [comment] 2016-01-27 18:39
No reason why I'm not using  linter-reek - like I said above, I'm new to linter and didn't know that one was available.  I'll install that one instead of the other one.  Sorry for any confusion or inconvenience this may have caused.

**Comment by Arcanemagus** [comment] 2016-01-27 18:43
No worries, glad it was a something simple to diagnose :wink:.
