### ISSUE TITLE
Uncaught TypeError: Invalid Point: (40, NaN)

### ISSUE THREAD

**Issue by avivbeeri** [atom-community/linter#1074] opened 2016-02-08 15:33 UTC
This sort of thing just seems to happen while I'm editing code :/

**Atom Version**: 1.4.3
**System**: Ubuntu 14.04.3
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.3

### Stack Trace

Uncaught TypeError: Invalid Point: (40, NaN)

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/point.js:63

TypeError: Invalid Point: (40, NaN)
    at Function.module.exports.Point.assertValid (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1015:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1003:20)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:204:46)
    at TextEditorMarkerLayer.module.exports.TextEditorMarkerLayer.markBufferRange (/usr/share/atom/resources/app.asar/src/text-editor-marker-layer.js:78:52)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/usr/share/atom/resources/app.asar/src/display-buffer.js:1100:38)
    at TextEditor.module.exports.TextEditor.markBufferRange (/usr/share/atom/resources/app.asar/src/text-editor.js:1339:59)
    at /home/aviv/.atom/packages/linter/lib/editor-linter.js:50:34
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at EditorLinter.addMessage (/home/aviv/.atom/packages/linter/lib/editor-linter.js:137:20)
    at /home/aviv/.atom/packages/linter/lib/linter-views.js:104:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (/home/aviv/.atom/packages/linter/lib/linter-views.js:102:11)
    at LinterViews.render (/home/aviv/.atom/packages/linter/lib/linter-views.js:59:10)
    at /home/aviv/.atom/packages/linter/lib/linter.coffee:39:14
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at MessageRegistry.updatePublic (/home/aviv/.atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (/home/aviv/.atom/packages/linter/lib/message-registry.js:24:16)
```

### Commands

```
     -3:11.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:01.8.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "highlight-line",
      "js-refactor",
      "refactor",
      "linter-htmlhint"
    ]
  },
  "linter": {
    "errorPanelHeight": 144
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.20.0
color-picker, v2.1.1
emmet, v2.4.1
emmet-snippets-compatibility, v1.0.4
file-icons, v1.6.14
linter, v1.11.3
linter-jscs, v3.4.4
linter-jshint, v1.3.0
minimap, v4.19.0
rename-tabs, v0.1.1
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2016-02-08 15:35
Dupe of #1048 #1053 #1058 #1059 #1061 #1062 #1065 #1068 #1060 #1063 #1064 #1066  #1069 #1070 #1071 #1072

**Closed by steelbrain** 2016-02-08 15:35 UTC
