### ISSUE TITLE
Uncaught TypeError: Invalid Point: (7, NaN)

### ISSUE THREAD

**Issue by crossjs** [atom-community/linter#1053] opened 2016-01-22 06:17 UTC
**Atom Version**: 1.4.0
**System**: Unknown Windows Version
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.3

### Stack Trace

Uncaught TypeError: Invalid Point: (7, NaN)

```
At C:\Users\Administrator\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\text-buffer\lib\point.js:63

TypeError: Invalid Point: (7, NaN)
    at Function.module.exports.Point.assertValid (C:\Users\Administrator\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\text-buffer\lib\point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (C:\Users\Administrator\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1015:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (C:\Users\Administrator\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1003:20)
    at MarkerLayer.module.exports.MarkerLayer.markRange (C:\Users\Administrator\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\text-buffer\lib\marker-layer.js:204:46)
    at TextEditorMarkerLayer.module.exports.TextEditorMarkerLayer.markBufferRange (C:\Users\Administrator\AppData\Local\atom\app-1.4.0\resources\app.asar\src\text-editor-marker-layer.js:78:52)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (C:\Users\Administrator\AppData\Local\atom\app-1.4.0\resources\app.asar\src\display-buffer.js:1100:38)
    at TextEditor.module.exports.TextEditor.markBufferRange (C:\Users\Administrator\AppData\Local\atom\app-1.4.0\resources\app.asar\src\text-editor.js:1339:59)
    at C:/Users/Administrator/.atom/packages/linter/lib/editor-linter.js:50:34
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Administrator\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Administrator\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at EditorLinter.addMessage (C:/Users/Administrator/.atom/packages/linter/lib/editor-linter.js:137:20)
    at C:/Users/Administrator/.atom/packages/linter/lib/linter-views.js:104:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (C:/Users/Administrator/.atom/packages/linter/lib/linter-views.js:102:11)
    at LinterViews.render (C:/Users/Administrator/.atom/packages/linter/lib/linter-views.js:59:10)
    at file:///C:/Users/Administrator/.atom/packages/linter/lib/linter.coffee:39:14
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Administrator\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Administrator\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at MessageRegistry.updatePublic (C:/Users/Administrator/.atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (C:/Users/Administrator/.atom/packages/linter/lib/message-registry.js:24:16)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "about",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "metrics",
      "release-notes",
      "atom-mac-terminal"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "linter": {
    "statusIconScope": "File"
  }
}
```

### Installed Packages

```coffee
# User
editorconfig, v1.2.4
jsdoc-generator, v0.1.10
jsformat, v0.9.0
language-babel, vundefined
language-javascript-jsx, v0.3.7
linter, v1.11.3
linter-eslint, v5.2.7
linter-jshint, v1.2.2
minimap, v4.19.0
pigments, v0.20.0
project-manager, v2.7.3
svn, v0.0.9
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment] 2016-01-22 20:55
Closing as a duplicate of #1048, if you have a file that reproduces this though can you _please_ post that over there? We haven't been able to reproduce it so we can't fix it.

**Closed by Arcanemagus** 2016-01-22 20:55 UTC
