### ISSUE TITLE
Uncaught TypeError: Invalid Point: (85, NaN)

### ISSUE THREAD

**Issue by theorm** [atom-community/linter#1070] opened 2016-02-05 00:01 UTC
[Enter steps to reproduce below:]

1. Open a javascript project
2. Make sure `jshint` linter is enabled
3. Start opening files
4. On one of the first files linter errors out
5. Linter does not work anymore until editor is restarted

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.2
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.3

### Stack Trace

Uncaught TypeError: Invalid Point: (85, NaN)

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63

TypeError: Invalid Point: (85, NaN)
    at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1015:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1003:20)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:204:46)
    at TextEditorMarkerLayer.module.exports.TextEditorMarkerLayer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker-layer.js:78:52)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1100:38)
    at TextEditor.module.exports.TextEditor.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1339:59)
    at /Users/roman/.atom/packages/linter/lib/editor-linter.js:50:34
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at EditorLinter.addMessage (/Users/roman/.atom/packages/linter/lib/editor-linter.js:137:20)
    at /Users/roman/.atom/packages/linter/lib/linter-views.js:104:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (/Users/roman/.atom/packages/linter/lib/linter-views.js:102:11)
    at LinterViews.render (/Users/roman/.atom/packages/linter/lib/linter-views.js:59:10)
    at /Users/roman/.atom/packages/linter/lib/linter.coffee:39:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at MessageRegistry.updatePublic (/Users/roman/.atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (/Users/roman/.atom/packages/linter/lib/message-registry.js:24:16)
```

### Commands

```
     -0:43.6.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:38.9.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:37.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:35 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:34.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:32.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:30.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:26.8.0 core:close (atom-text-editor.editor.is-focused)
     -0:20.2.0 pane:split-right (atom-text-editor.editor.is-focused)
     -0:16.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:15.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:13.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:12.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:10.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:09.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:08.8.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete",
      "atom-ctags",
      "block-comment",
      "linter-jscs"
    ],
    "followSymlinks": true,
    "themes": [
      "seti-ui",
      "monokai"
    ]
  },
  "linter": {
    "ignoredLinterErrors": [
      "jshint"
    ],
    "lintOnChangeInterval": 2000
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-beautify, v0.28.21
atom-ternjs, v0.13.2
atom-typescript, v8.2.0
auto-indent, v0.5.0
color-picker, v2.1.1
compare-files, v0.6.2
language-docker, v1.1.6
language-jade, v0.6.3
language-nginx, v0.6.1
language-scala, v1.1.6
linter, v1.11.3
linter-jshint, v1.3.0
linter-scalac, v1.3.1
monokai, v0.18.0
pretty-json, v0.4.1
project-manager, v2.7.6
seti-ui, v0.8.1

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment] 2016-02-05 00:09
Without a file to verify what is going on we can't verify this exactly, but as you mention `linter-jshint` as the linter provider you are seeing this with I'm assuming you are either running into the [`camel_case` bug](https://github.com/jshint/jshint/pull/2846), or the [`esprima` parsing issue](https://github.com/jquery/esprima/issues/1457).

**Comment by Arcanemagus** [comment] 2016-02-05 00:10
I would recommend you check out a newer and more advanced Javascript linter such as `eslint` or `jscs`.

**Comment by steelbrain** [comment] 2016-02-05 16:40
Dupe of #1048 #1053 #1058 #1059 #1061 #1062 #1065 #1068 #1060 #1063 #1064 #1066  #1069

**Closed by steelbrain** 2016-02-05 16:40 UTC
Labels: external
