### ISSUE TITLE
Determine a way to not count the leading whitespace on a blank line as trailing whitespace in the linter

### ISSUE THREAD

**Issue by mehcode** [atom-community/linter#869] opened 2015-08-26 21:03 UTC
What I'd prefer is that until I start typing non-whitespace the cursor moves but does not actually insert whitespace.

---

https://github.com/atom/atom/pull/8514#issuecomment-135164019
> @mehcode No, there is currently no support for "virtual whitespace" in the Atom data model. There is/was an Issue for adding it, but I can't find it right now.

---

https://github.com/atom/atom/pull/8514#issuecomment-135164221
> I think this would add a lot of complexity, both in the implementation and for the user and package author.
> 
> An alternative solution might be to pass the current cursor positions to the linter so that it can filter out warnings about whitespace on the lines where the cursors are.

**Comment by steelbrain** [comment] 2015-08-26 21:11
What if I told you, that this linter package does nothing but trigger the providers :smiley: 
I believe this belongs to providers instead of the core.

**Comment by mehcode** [comment] 2015-08-26 21:15
What if I told you that this makes me incredibly sad. You're telling me that _every_ _single_ _linter_ would need to be updated for this basic thing that occurs in all of them (that happen to have a rule that matches trailing whitespace)?

**Comment by Arcanemagus** [comment] 2015-08-26 21:37
Let me see if I'm interpreting what is going on here:

0. You open a file
0. Start typing, eventually hitting a line that starts with only whitespace
0. You have `lintOnFly` enabled, and one of your `linter-*` providers supports that... and is complaining about there being "trailing" whitespace

Is that what is happening here?

----

If so I think this is a misunderstanding on your part: As far as the linter is concerned it has no idea you are still in the middle of writing the file, it just knows it was asked to tell you what was wrong with the file _when the lint was triggered_. Since all it sees is a bunch of whitespace at the "end" of the file, it's telling you as such.

The `linter` package just provides the UI elements and framework for triggering the individual `linter-*` packages. In turn they simply run the actual linter programs (`flake8`, `phpcs`, `rubocop`, ...), parse the output, and give it back to `linter` in a standardized format. To "fix" this as you are requesting would need to go all the way down to every single linter program, which is a monumental task that would involve everyone working on every possible linter program... near impossible for something that isn't really an issue in the first place. There is some possibility of doing as @maxbrunsfeld suggested but as this is likely only to be an "invalid" error in `lintOnFly` circumstances by the time the linter returns results, they are filtered, and the "invalid" message(s) filtered out, the user will probably have already moved on.

You can "fix" this by disabling `lintOnFly`, which means it would only trigger a lint when you save the file. Or you can simply keep typing and that message should go away.

As to another part of why that is happening: `linter` uses Atom's "idle" even to figure out when it should trigger a lint on the fly. Unfortunately although that should be a relatively reasonable delay (I think it is supposed to be 300ms?) it seems on several people's installation it is essentially instant.

**Comment by mehcode** [comment] 2015-08-26 22:10
> Is that what is happening here?

Correct.

---

I understand its a _hard_ thing to fix that is barely an issue. But it does fall under what I would call _polish_ and I'd say that should be fixed, eventually.

> As to another part of why that is happening: linter uses Atom's "idle" even to figure out when it should trigger a lint on the fly. [...]

If it was an actual 300ms delay I would care significantly less as I probably wouldn't even notice it. It seems to be near-instant on my machine.

**Comment by steelbrain** [comment] 2015-09-19 13:45
Sorry bud, but I am gonna have to close this one as invalid. Because we can't filter the messages provided by linter and ignore the message which says there's whitespace at point x, 'cause for each linter it's way of saying is gonna be different, and it's gonna be an unnecessary check as it's "working as intended", You haven't wrote anything on that line and it's got whitespaces and it's telling you that there's whitespaces. Seems perfectly fine by me, alternatively you can disable that linter's "feature" of notifying you of unnecessary whitespaces as atom automatically trims the whitespaces on every save.

**Closed by steelbrain** 2015-09-19 13:45 UTC
