### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('u...

### ISSUE THREAD

**Issue by bogem** [atom-community/linter#822] opened 2015-08-11 03:53 UTC
**Atom Version**: 1.0.5
**System**: Mac OS X 10.10.4
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.3.4

### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('unterminated-string meets end of fil') contains HTML space characters, which are not valid in tokens.

```
At /Users/user/.atom/packages/linter/lib/views/message.coffee:30

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('unterminated-string meets end of fil') contains HTML space characters, which are not valid in tokens.
  at Error (native)
  at Function.Message.renderRibbon (/Users/user/.atom/packages/linter/lib/views/message.coffee:30:18)
  at linter-message.Message.attachedCallback (/Users/user/.atom/packages/linter/lib/views/message.coffee:5:26)
  at linter-panel.<anonymous> (/Users/user/.atom/packages/linter/lib/views/bottom-panel.js:49:12)
  at Array.forEach (native)
  at linter-panel.updateMessages (/Users/user/.atom/packages/linter/lib/views/bottom-panel.js:48:14)
  at LinterViews.renderPanelMessages (/Users/user/.atom/packages/linter/lib/linter-views.coffee:107:12)
  at LinterViews.render (/Users/user/.atom/packages/linter/lib/linter-views.coffee:42:6)
  at /Users/user/.atom/packages/linter/lib/linter-plus.coffee:29:14
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at MessageRegistry.updatePublic (/Users/user/.atom/packages/linter/lib/message-registry.js:104:20)
  at UpdateMessages (/Users/user/.atom/packages/linter/lib/message-registry.js:35:17)

```

### Commands

```
     -0:46.7.0 core:move-left (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:46.5.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
 30x -0:45.7.0 core:move-right (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:42.2.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:41.6.0 core:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:41.1.0 core:move-up (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
 13x -0:40.9.0 core:move-left (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
 20x -0:38.6.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:31.5.0 core:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -0:31.2.0 autocomplete-plus:confirm (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -0:22.7.0 core:save (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:15.5.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:12.3.0 core:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -0:12.1.0 autocomplete-plus:confirm (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
  8x -0:07.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:01.4.0 core:save (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "relative-numbers"
    ]
  },
  "linter": {
    "lintOnFly": false,
    "showErrorPanel": false
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-ruby, v0.1.0
git-plus, v5.3.4
linter, v1.3.4
linter-rubocop, v0.3.1
linter-ruby, v1.0.0
pigments, v0.9.3
relative-line-numbers, v0.1.5
tab-numbers, v0.2.0
vim-mode, v0.57.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2015-08-11 07:58
I thought it had been fixed, can you please provide us some repro case?

**Comment by bogem** [comment] 2015-08-11 10:36
@steelbrain This bug has occured only one time - after I installed your new update. But after a while, it hasn't occured

**Comment by Troush** [comment] 2015-08-11 10:49
Can confirm multiple occurs:

Atom: 1.0.2
System: 14.04.1-Ubuntu
Thrown From: linter package, v1.3.4

```
Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('unknown-type of ') contains HTML space characters, which are not valid in tokens.
  at Error (native)
  at Function.Message.renderRibbon (/home/troush/.atom/packages/linter/lib/views/message.coffee:30:18)
  at linter-message.Message.attachedCallback (/home/troush/.atom/packages/linter/lib/views/message.coffee:5:26)
  at linter-panel.<anonymous> (/home/troush/.atom/packages/linter/lib/views/bottom-panel.js:49:12)
  at Array.forEach (native)
  at linter-panel.updateMessages (/home/troush/.atom/packages/linter/lib/views/bottom-panel.js:48:14)
  at LinterViews.renderPanelMessages (/home/troush/.atom/packages/linter/lib/linter-views.coffee:107:12)
  at LinterViews.render (/home/troush/.atom/packages/linter/lib/linter-views.coffee:42:6)
  at /home/troush/.atom/packages/linter/lib/linter-plus.coffee:29:14
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at MessageRegistry.updatePublic (/home/troush/.atom/packages/linter/lib/message-registry.js:104:20)
  at UpdateMessages (/home/troush/.atom/packages/linter/lib/message-registry.js:35:17)
```

**Comment by Arcanemagus** [comment] 2015-08-11 17:27
@Troush do you have steps to reproduce it?

**Comment by adamvaughan** [comment] 2015-08-11 23:33
This bit of fat-fingered ruby reproduces it for me

```ruby
hash_missing_equals {
  'key' => 'value',
  'other key' => 'value missing closing tick
}
```

**Comment by KurtRMueller** [comment] 2015-08-12 00:18
For me, this happens regarding rails haml views.

@Arcanemagus For me, this can simply be reduced by clicking anywhere in the file. I have vim-mode turned on btw.

**Comment by bernardogfilho** [comment] 2015-08-12 01:40
As @KurtRMueller reported, this is happening everytime I do some action in a `haml` file.

**Comment by Arcanemagus** [comment] 2015-08-12 03:06
So at least with the code @adamvaughan posted (thanks!) it looks like this is a mistake in the regex they are using that is causing this. It's trying to use "unterminated string meets end of fil" as the error type, which obviously doesn't match "error" :wink:.

Working on a better regex for that.

**Comment by steelbrain** [comment] 2015-08-12 07:04
A confirmed fix is up in https://github.com/atom-community/linter/pull/827

**Comment by steelbrain** [comment] 2015-08-13 15:49
Closing as invalid since it's a provider bug.

**Closed by steelbrain** 2015-08-13 15:49 UTC
Labels: invalid
