### ISSUE TITLE
Uncaught TypeError: Invalid Point: (31, NaN)

### ISSUE THREAD

**Issue by frontyard** [atom-community/linter#1072] opened 2016-02-06 08:57 UTC
[Enter steps to reproduce below:]

1. I was editing a file and did undo/redo several times.

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.3

### Stack Trace

Uncaught TypeError: Invalid Point: (31, NaN)

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63

TypeError: Invalid Point: (31, NaN)
    at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1015:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1003:20)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:204:46)
    at TextEditorMarkerLayer.module.exports.TextEditorMarkerLayer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker-layer.js:78:52)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1100:38)
    at TextEditor.module.exports.TextEditor.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1339:59)
    at /Users/nedim/.atom/packages/linter/lib/editor-linter.js:50:34
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at EditorLinter.addMessage (/Users/nedim/.atom/packages/linter/lib/editor-linter.js:137:20)
    at /Users/nedim/.atom/packages/linter/lib/linter-views.js:104:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (/Users/nedim/.atom/packages/linter/lib/linter-views.js:102:11)
    at LinterViews.render (/Users/nedim/.atom/packages/linter/lib/linter-views.js:59:10)
    at /Users/nedim/.atom/packages/linter/lib/linter.coffee:39:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at MessageRegistry.updatePublic (/Users/nedim/.atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (/Users/nedim/.atom/packages/linter/lib/message-registry.js:24:16)
```

### Commands

```
     -3:15.7.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -3:04.9.0 tern:definition (atom-text-editor.editor.is-focused)
     -2:52 tern:references (atom-text-editor.editor.is-focused)
     -2:34.2.0 tern:openConfig (atom-text-editor.editor.is-focused)
     -2:02.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -1:40.6.0 core:select-right (atom-text-editor.editor.mini.is-focused)
     -1:35.4.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -1:12.1.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -1:10.6.0 core:undo (atom-text-editor.editor.is-focused)
     -1:10 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:08.3.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -0:53.9.0 core:undo (atom-text-editor.editor.is-focused)
     -0:19.6.0 core:select-all (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:19 core:move-down (atom-text-editor.editor.is-focused)
  9x -0:17.8.0 core:undo (atom-text-editor.editor.is-focused)
     -0:08.7.0 core:redo (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
antialiased, v0.1.0
atom-handlebars, v1.3.0
atom-ternjs, v0.13.2
autocomplete-json, v1.5.0
build-gulp, v0.7.0
build-npm-apm, v0.8.0
color-picker, v2.1.1
css-color-underline, v1.0.1
linter, v1.11.3
linter-csslint, v1.2.0
linter-flexpmd, v0.1.9
linter-handlebars, v2.3.1
linter-jshint, v1.3.0
linter-sass-lint, v1.0.4
linter-tidy, v2.1.0
minimap, v4.19.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2016-02-08 15:35
Dupe of #1048 #1053 #1058 #1059 #1061 #1062 #1065 #1068 #1060 #1063 #1064 #1066  #1069 #1070 #1071

**Closed by steelbrain** 2016-02-08 15:35 UTC
