### ISSUE TITLE
Linter dies with underscore in variable name with   "camelcase": true

### ISSUE THREAD

**Issue by newmanw** [atom-community/linter#1057] opened 2016-01-25 18:54 UTC
Given the following code:

  var moment_broken = require('moment');

Dies with:

```
Uncaught TypeError: Invalid Point: (11, NaN)

TypeError: Invalid Point: (11, NaN)
    at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1015:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1003:20)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:204:46)
    at TextEditorMarkerLayer.module.exports.TextEditorMarkerLayer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker-layer.js:78:52)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1100:38)
    at TextEditor.module.exports.TextEditor.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1339:59)
    at /Users/wnewman/.atom/packages/linter/lib/editor-linter.js:50:34
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at EditorLinter.addMessage (/Users/wnewman/.atom/packages/linter/lib/editor-linter.js:137:20)
    at /Users/wnewman/.atom/packages/linter/lib/linter-views.js:104:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (/Users/wnewman/.atom/packages/linter/lib/linter-views.js:102:11)
    at LinterViews.render (/Users/wnewman/.atom/packages/linter/lib/linter-views.js:59:10)
    at /Users/wnewman/.atom/packages/linter/lib/linter.coffee:39:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at MessageRegistry.updatePublic (/Users/wnewman/.atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (/Users/wnewman/.atom/packages/linter/lib/message-registry.js:24:16)
```

If I set "camelcase": false the linter will not die.

**Comment by steelbrain** [comment] 2016-01-25 18:58
@newmanw This is actually a problem with your linter provider, can you tell us the name of packages you've installed?

**Comment by newmanw** [comment] 2016-01-25 19:38
https://atom.io/users/AtomLinter

**Comment by Arcanemagus** [comment] 2016-01-25 19:46
If you enable forcing ESNext parsing does the bug go away?

**Comment by newmanw** [comment] 2016-01-25 19:54
```javascript
esnext: true
```

Error still exist.

**Comment by Arcanemagus** [comment] 2016-01-25 20:16
Can you file an issue over on linter-jshint with that error as well as a file to reproduce the error with if at all possible?

I'm marking this as closed since it isn't an issue with `linter` itself.

**Closed by Arcanemagus** 2016-01-25 20:16 UTC
Labels: external, question
