### ISSUE TITLE
Uncaught TypeError: Invalid Point: (16, NaN)

### ISSUE THREAD

**Issue by eloiqs** [atom-community/linter#1066] opened 2016-02-04 02:39 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.3
**System**: Ubuntu 15.10
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.3

### Stack Trace

Uncaught TypeError: Invalid Point: (16, NaN)

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/point.js:63

TypeError: Invalid Point: (16, NaN)
    at Function.module.exports.Point.assertValid (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1015:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1003:20)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:204:46)
    at TextEditorMarkerLayer.module.exports.TextEditorMarkerLayer.markBufferRange (/usr/share/atom/resources/app.asar/src/text-editor-marker-layer.js:78:52)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/usr/share/atom/resources/app.asar/src/display-buffer.js:1100:38)
    at TextEditor.module.exports.TextEditor.markBufferRange (/usr/share/atom/resources/app.asar/src/text-editor.js:1339:59)
    at /home/eloi/.atom/packages/linter/lib/editor-linter.js:50:34
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at EditorLinter.addMessage (/home/eloi/.atom/packages/linter/lib/editor-linter.js:137:20)
    at /home/eloi/.atom/packages/linter/lib/linter-views.js:104:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (/home/eloi/.atom/packages/linter/lib/linter-views.js:102:11)
    at LinterViews.render (/home/eloi/.atom/packages/linter/lib/linter-views.js:59:10)
    at /home/eloi/.atom/packages/linter/lib/linter.coffee:39:14
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at MessageRegistry.updatePublic (/home/eloi/.atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (/home/eloi/.atom/packages/linter/lib/message-registry.js:24:16)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
editorconfig, v1.2.4
emmet, v2.4.1
linter, v1.11.3
linter-csslint, v1.2.0
linter-htmlhint, v1.0.2
linter-jshint, v1.3.0
linter-php, v1.1.7
minimap, v4.19.0
seti-syntax, v0.4.1
seti-ui, v0.8.1

# Dev
No dev packages
```

**Comment by Arcanemagus** [comment] 2016-02-04 18:31
Without a file to verify what is going on we can't verify this exactly, but as I see one of your providers is `linter-jshint` I'm assuming you are either running into the `camel_case` bug, or the `esprima` parsing issue.

**Comment by steelbrain** [comment] 2016-02-05 16:40
Dupe of #1048 #1053 #1058 #1059 #1061 #1062 #1065 #1068 #1060 #1063 #1064 #1066

**Closed by steelbrain** 2016-02-05 16:40 UTC
Labels: external
