### ISSUE TITLE
linter only working on the latest saved pane

### ISSUE THREAD

**Issue by lukeaus** [atom-community/linter#811] opened 2015-08-05 21:33 UTC
if you have 2 panes open in Atom then the linter only works on the last saved pane

Not sure if this is expected behaviour or not. Would be great if it could lint and show errors for all visible tabs.

Tested on a fresh install of Atom 1.0.4 
Packages:
core packages +
Linter 1.3.1
Linter-pylama 0.1.5

issue also exists when tested with 
Atom 1.0.4 
Packages:
core packages +
Linter 1.3.1
linter-flake8 v1.6.0

Note: 'Lint on fly' is enabled in Linter

Tested  on osx 10.10.4

**Comment by steelbrain** [comment] 2015-08-05 21:34
Dupe of https://github.com/atom-community/linter/issues/711

**Comment by lukeaus** [comment] 2015-08-05 21:39
@steelbrain that looks like a completely different issue to what I am talking about.
My issue is to do with linting only working for the currently active pane.
That issue is about tooltips overlapping into another pane.

I have attached a screenshot below
![downloads - atom 2015-08-06 07-38-04](https://cloud.githubusercontent.com/assets/5635204/9098597/3c986b16-3c0e-11e5-9161-d80b28c943ad.jpg)

**Comment by steelbrain** [comment] 2015-08-05 21:40
Right.

**Comment by steelbrain** [comment] 2015-09-28 10:23
I think I've fixed it in the master, you can expect a release soon.

**Comment by steelbrain** [comment] 2015-10-02 13:21
Fix release has been published

**Closed by steelbrain** 2015-10-02 13:21 UTC

**Comment by Arcanemagus** [comment] 2015-10-02 16:31
Should this really have been "fixed"? If I have two tabs (with different files!) open I definitely don't want it spending time linting a file I'm not currently editing.

What event would even trigger it? There would be no save events, and no changed text events fired on the inactive tab.

**Comment by steelbrain** [comment] 2015-10-02 16:33
@Arcanemagus previously, if you had two tabs with different files and saved one, switched to the other, the decorations on the first one will be removed and you'll have to make it active to see the underlines or gutter highlights. Currently we can highlight multiple panes at once. But only after we get errors from the providers which happens in `linter:lint` which is not toggled unless you save or edit a file.

**Comment by Arcanemagus** [comment] 2015-10-02 16:42
Ah, that makes perfect sense.
