### ISSUE TITLE
Uncaught TypeError: Invalid Point: (52, NaN) with file

### ISSUE THREAD

**Issue by fyyyyy** [atom-community/linter#1071] opened 2016-02-05 09:47 UTC
[Enter steps to reproduce below:]

The file:

```javascript

(function() {
  'use strict';

  angular
    .module('app')
    .controller('MainController', [
        '$scope',
        'polygonService',
        'mapService',
        'cityService',
        '$filter',
        '$state',
        'polygon',
        MainController
    ]);

  /** @ngInject */
  function MainController(
      $scope,
      polygonService,
      mapService,
      cityService,
      $filter,
      $state,
      polygon
  ){

      if(!$state.is('polygons.details')) {
          cityService.setDefault();
      }

      angular.extend($scope, {
          polygon: polygon,
          polygons: polygonService,
          search: {
              zoneType: 'all',
              status: 'all'
          }
      });



      $scope.$watch(function() {

          return cityService.getCurrent();

      }, function(currentCity) {

          if(currentCity) {
              // get new polygons
              $scope.polygons.setAll({
                  filter: {
                      'cityId': currentCity.c_id
                  }
              });
          }

      }, true);

  }
})();

```

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.11.3

### Stack Trace

Uncaught TypeError: Invalid Point: (52, NaN)

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63

TypeError: Invalid Point: (52, NaN)
    at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1015:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1003:20)
    at MarkerLayer.module.exports.MarkerLayer.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:204:46)
    at TextEditorMarkerLayer.module.exports.TextEditorMarkerLayer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker-layer.js:78:52)
    at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1100:38)
    at TextEditor.module.exports.TextEditor.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1339:59)
    at /Users/tree/.atom/packages/linter/lib/editor-linter.js:50:34
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at EditorLinter.addMessage (/Users/tree/.atom/packages/linter/lib/editor-linter.js:137:20)
    at /Users/tree/.atom/packages/linter/lib/linter-views.js:104:22
    at Array.forEach (native)
    at LinterViews.notifyEditorLinters (/Users/tree/.atom/packages/linter/lib/linter-views.js:102:11)
    at LinterViews.render (/Users/tree/.atom/packages/linter/lib/linter-views.js:59:10)
    at /Users/tree/.atom/packages/linter/lib/linter.coffee:39:14
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at MessageRegistry.updatePublic (/Users/tree/.atom/packages/linter/lib/message-registry.js:84:18)
    at UpdateMessages (/Users/tree/.atom/packages/linter/lib/message-registry.js:24:16)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "language-javascript-jsx",
      "node-debugger",
      "language-javascript-semantic"
    ],
    "themes": [
      "one-light-ui",
      "monday-syntax"
    ]
  },
  "linter": {
    "showInfoMessages": true,
    "statusBar": "Show error of the selected line"
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.2.1
javascript-snippets, v1.2.0
language-javascript-better, v1.7.1
linter, v1.11.3
linter-eslint, v6.0.0
linter-jshint, v1.3.0
monday-syntax, v0.1.4
react, v0.14.1
webbox-color, v0.5.9

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2016-02-05 16:39
Dupe of #1048 #1053 #1058 #1059 #1061 #1062 #1065 #1068 #1060 #1063 #1064 #1066  #1069 #1070 #1071

**Closed by steelbrain** 2016-02-05 16:39 UTC
