### ISSUE TITLE
Warnings not shown

### ISSUE THREAD

**Issue by tomitrescak** [atom-community/linter#796] opened 2015-08-03 08:17 UTC
I have just updated Tslint and linter and my warnings from TsLint are no longer visible.
There is a yellow rectangle on the line where warning should appear, but I cannot access it.
How can I bring warnings back? (See the missing semicolumn)

![screen shot 2015-08-03 at 18 12 55](https://cloud.githubusercontent.com/assets/2682705/9033583/e217d900-3a0b-11e5-8da6-41ed2768a7d5.png)

Thanks!

**Comment by steelbrain** [comment] 2015-08-03 09:59
I am unable to reproduce with `linter-jshint`, `linter-eslint` and `atom-hack`. You might wanna report this in that linter :)

**Comment by aar0nr** [comment] 2015-08-03 14:07
@tomitrescak - I'm guessing that tslint has API depreciations that no longer work with atom v1.3. You'll have to stick with v1.2.4 until the tslint plugin is updated.

**Comment by steelbrain** [comment] 2015-08-03 14:09
SideNote: The yellow rectangle is from atom's git diff, not from linter.

**Comment by IanEdington** [comment] 2015-08-05 02:19
I'm having the same issue but with linter-jsonlint and linter-pylint. js-lint however works.

No deprications showing. Let me what info you want. Please be specific, I am not 

![screen shot 2015-08-04 at 9 58 00 pm](https://cloud.githubusercontent.com/assets/6425087/9076985/caaab2e2-3af6-11e5-852f-ff0f141dfe52.png)
![screen shot 2015-08-04 at 9 58 42 pm](https://cloud.githubusercontent.com/assets/6425087/9076984/caa2f980-3af6-11e5-8405-88c10f724304.png)

**Comment by mrakjos** [comment] 2015-08-07 08:52
I have same problem with linter-jsxhint on last OSX

![screen shot 2015-08-07 at 10 41 17](https://cloud.githubusercontent.com/assets/7734088/9132061/f74c71cc-3cf0-11e5-8274-c74e54eab91c.png)

Reinstal Atom, remove .atom/ don't fix it. linter-less works fine.

**Comment by steelbrain** [comment] 2015-08-07 08:55
@mrakjos You didn't have to reinstall atom :stuck_out_tongue: 
You could've just downgraded linter using `apm install linter@1.2.4`

**Comment by steelbrain** [comment] 2015-08-10 12:05
Closing based on comment above.

**Closed by steelbrain** 2015-08-10 12:05 UTC

**Comment by IanEdington** [comment] 2015-08-10 12:46
Thank you @steelbrain. I downgraded linter to 1.2.4 painlessly using apm. I have been very impressed with Atom.
