### ISSUE TITLE
Warning line and column is wrong.

### ISSUE THREAD

**Issue by jiegec** [atom-community/linter#1016] opened 2015-12-12 09:58 UTC
If Chinese characters are in one line, if the linter reports a warning after the character in the same line, it have the same offest as the numbers of chinese characters. It may be caused by different methods of counting characters. It seems Chinese character equals to one in atom. But it equals to two in utf8.

**Comment by steelbrain** [comment] 2015-12-12 09:59
Thank you for the bug report. This linter is just the base and provides an API to other linters to show messages in editor. The bug that you've encountered is a bug in the provide and not in the linter itself.

Can you tell us which language were you editing when you got this error and which linter providers you've installed?

**Comment by jiegec** [comment] 2015-12-12 11:44
LaTeX. linter-chktex. This problem may appear in other linters as well.

**Comment by Arcanemagus** [comment] 2015-12-13 11:04
Can you provide an example file to simplify testing?

**Comment by jiegec** [comment] 2015-12-13 13:27
This line:
```
    \pause\item It is widely used in academia (学术界 \textipa{/""\ae{}k@"di:mI9/}).
```
Chktex has the warning for "\"\"" but the red line under text is under "t\".

**Comment by Arcanemagus** [comment] 2015-12-17 21:15
Looks like this is a duplicate of https://github.com/nscaife/linter-chktex/issues/23.

**Closed** 2015-12-17 21:16 UTC
Labels: question
