### ISSUE TITLE
Package activation time

### ISSUE THREAD

**Issue by csholmq** [atom-community/linter#1028] opened 2015-12-16 13:43 UTC
![image](https://cloud.githubusercontent.com/assets/1297882/11842334/53525de6-a403-11e5-921b-132ada7234df.png)

Takes ~350 ms to activate the package. How come?

**Comment by steelbrain** [comment] 2015-12-16 13:44
Dupe of #1026

**Closed by steelbrain** 2015-12-16 13:44 UTC

**Comment by csholmq** [comment] 2015-12-16 13:45
Sorry about that!

**Comment by steelbrain** [comment] 2015-12-16 13:46
It's okay, happens to all of us :)
