### ISSUE TITLE
Latest linter 1.3.0 crashes dartlang plugin

### ISSUE THREAD

**Issue by eseidel** [atom-community/linter#794] opened 2015-08-02 18:19 UTC
The issue is likely with dartlang:
https://github.com/dart-atom/dartlang/issues/158
but thought you should be aware regardless.  Feel free to close.

Downgrading to 1.2.4 fixes the issue for dartlang.  @devoncarew notes that he'll update the package on Monday, however other linter-dependent packages may have broken similarly.

**Comment by steelbrain** [comment] 2015-08-02 18:20
I have tried quite a few providers and they are all working fine for me, can you please provide a repro case?

**Comment by eseidel** [comment] 2015-08-02 18:22
I had a super simple Dart project:
https://github.com/dart-atom/dartlang/issues/158#issuecomment-127048270
and had the latest dart package from homebrew installed.

I suspect we'll know much more once Devon has a chance to debug.  Again, feel free to close this if you aren't getting other reports from other linter projects.  The error looks like the dartlang plugin was attempting to wrap a null exception object.

**Comment by steelbrain** [comment] 2015-08-02 18:25
@eseidel I won't close it unless I am **sure** it's not a bug :)
Anyways, the trace in that error message is a bit misleading, there is no such thing as `scope` near those lines.

**Comment by steelbrain** [comment] 2015-08-02 18:27
@eseidel Can you try a few things and tell me if they work for you? You'll find me in #linter of atom's slack.

**Comment by steelbrain** [comment] 2015-08-02 18:45
Closing based on https://github.com/dart-atom/dartlang/issues/158#issuecomment-127053031

**Closed by steelbrain** 2015-08-02 18:45 UTC
