### ISSUE TITLE
Duplicate errors not being cleared

### ISSUE THREAD

**Issue by zyklus** [atom-community/linter#854] opened 2015-08-19 12:58 UTC
eslint is currently, in some cases, throwing the exact same line/col/error message more than once.  If this happens, the linter doesn't clear the subsequent errors and there is a error badge forever left behind until the line is deleted.

![repeated-errors](https://cloud.githubusercontent.com/assets/320562/9356671/e4d1984c-46b4-11e5-84c4-5f7e550c0a47.gif)

**Comment by steelbrain** [comment] 2015-08-20 18:27
It's already fixed in the latest released, fixed it days ago.

**Closed by steelbrain** 2015-08-20 18:27 UTC

**Comment by zyklus** [comment] 2015-08-22 03:29
This exists in 1.4.3 which is the newest published version.

**Comment by steelbrain** [comment] 2015-08-22 03:30
@zyklus It's highly unlikely that this is still present, I fixed it myself. Can you provide a repro case please?

**Comment by zyklus** [comment] 2015-08-22 03:51
@steelbrain -- Sorry, it might not be exactly the same issue (the gif I posted is no longer reproducible), but it's similar:

![err](https://cloud.githubusercontent.com/assets/320562/9422380/ff708d64-48c3-11e5-90fb-432beeb38210.gif)

Also note that yesterday (after I updated) it was caching the errors after I closed and re-opened a file (though I can't reproduce this at the moment).

**Comment by steelbrain** [comment] 2015-08-22 10:13
@zyklus ah, that is a not a bug. It's a feature :smiley: 
So we have two types of lintings, `lintOnFly` and on save. If you have disabled `lintOnFly` or if your provider doesn't support it, it means your files will only be validated on save.

**Comment by zyklus** [comment] 2015-08-22 10:29
Both of these are going through `lintOnFly` though :)

**Comment by steelbrain** [comment] 2015-08-22 10:30
@zyklus it means that the provider doesn't support it then.

**Comment by zyklus** [comment] 2015-08-22 10:34
Oh!  Okay, I know what's going on here.

Okay, in my most recent gif:

- The entire file is linted with eslint when in the backticks (this is a different bug)
- The rest of the file can't be linted at all (I don't have a markdown linter)
- When I blow away the js code block, the linter is now stuck in a state where it _can't_ ever clear the errors

There are multiple things going on here, but I think this package takes at least some of the responsibility ;)

**Comment by Arcanemagus** [comment] 2015-08-24 17:11
Point 1 is related to https://github.com/atom/language-gfm/issues/121
Point 2 isn't really an issue, just something that somebody needs to implement (if such a thing even exists)
Point 3 is really the only thing that would be fixable here.

**Comment by steelbrain** [comment] 2015-08-24 17:14
About point 3, it's stuck in that state 'cause the js linter that reported those issues won't be triggered anymore as there isn't any js blocks in the file. I can't think of a good way to deal with it other than just closing/re-opening the panel
